### ISSUE TITLE
Minor cosmetic issue - minimized window in safari 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#118]
While testing in each browser I noticed this when resizing the window. Random transaction link at the bottom of the page looses padding when minimizing window, very minor cosmetic P4 bug prioritize as you see fit.

<img width="768" alt="Screen Shot 2020-05-13 at 12 06 17 PM" src="https://user-images.githubusercontent.com/49165468/81837057-510d5680-9512-11ea-877f-c54d17570565.png">

**Comment by aulneau** [comment]
will be fixed with #115

**Comment by aulneau** [comment]
This has been resolved
