### ISSUE TITLE
Add FAQs to the footer

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#119]
As per discussion [in this doc](https://paper.dropbox.com/doc/Draft-Explorer-FAQs--Az7z4LacBtLa2iwNl2E7g6uvAQ-YzOiSXCqSLW9wLA8S4dy7), we would like to add a link to the Explorer FAQs.

The final URL is TBD (@markmhx to input), but I wanted to put the issue in the backlog.

**Comment by markmhx** [comment]
I'm happy to decide and provide a URL for this unless any of you have a particular preference.

**Comment by agraebe** [comment]
Based on the conversation in the doc, the URL would be `www2.blockstack.org/explorer/faq` as per Mark's suggestion.
