### ISSUE TITLE
Block time does not show an exact time stamp 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#120]
Timestamp does not show an exact time stamp like 11:09:15 it shows the time from  3 hours ago. Should we be showing exact time.

<img width="1256" alt="Screen Shot 2020-05-13 at 3 10 00 PM" src="https://user-images.githubusercontent.com/49165468/81854700-52e41380-952c-11ea-8c93-5b01ef321520.png">

**Comment by agraebe** [comment]
This showed up when we discussed how to react to bug reports. It could happen that the tx id isn't available anymore when we review it (restart of the node). Is there a way to troubleshoot in that context?

**Comment by aulneau** [comment]
I think we can add a tooltip hover to show the exact timestamp down to the seconds.

**Comment by agraebe** [comment]
@timstackblock in the issue template, we should ask them to hover over the block field to explicitly provide that input as part of the bug report, right?
