### ISSUE TITLE
Showing the build/version id in the logs

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#121]
This is likely a lower priority, but we would potentially ask users to share their logs when they submit a bug report.

It would be great to print the build/version id of the Explorer in the logs, so we could identify what version the reported issue is referencing.

**Comment by aulneau** [comment]
> It would be great to print the build/version id of the Explorer in the logs, so we could identify what version the reported issue is referencing.

I don't really know what this would be, there is no build / version for the explorer. We could make something up, but I don't know what good that would do.

**Comment by agraebe** [comment]
I'm assuming it's not solving a big problem, but knowing if the bug reported happened with an older version might be telling when we troubleshoot more difficult bugs. I'll let you make the call. I mainly wanted to make sure we evaluate the idea.

A build version could be based on the latest commit (https://github.com/nexdrew/next-build-id), for instance.

**Comment by aulneau** [comment]
sure, I can see some value in that, I think it's a lower priority but could be helpful.

**Comment by aulneau** [comment]
I don't think this is a priority currently, and I don't know exactly the benefit we'd get from this right now. Closing (feel free to reopen if there is value)
