### ISSUE TITLE
minor bug Memo field contains the works faucet and displays incorrectly in FF browser

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#123]
Minor bug Memo field renders incorrectly in mozilla FF
faucet message displays incorrectly the T returns to the second line but looks normal in chrome

Returns the T on the second line in FF
<img width="1370" alt="Screen Shot 2020-05-13 at 3 13 35 PM" src="https://user-images.githubusercontent.com/49165468/81948135-65fbef80-95cf-11ea-96ce-293563e53fbf.png">

Looks good in chrome

<img width="1432" alt="Screen Shot 2020-05-14 at 10 43 03 AM" src="https://user-images.githubusercontent.com/49165468/81948711-09e59b00-95d0-11ea-8870-cb0024173afc.png">

**Comment by zone117x** [comment]
A random aside: how in the world do FF and Chrome have a rendering difference like this in 2020 😑

**Comment by aulneau** [comment]
yeah for some reason in firefox a bunch of a chars are being rendered lol
