### ISSUE TITLE
When sidecar is restarted frontend will show 53 bits error

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#124]
If I attempt to send stack to an address when I deployed a contract that has been deleted because sidecar has been restarted the frontend will show a 53 bits error. 

This is more of a placeholder for a known issue than a bug. I think we may see several reports of this from discorse so users an comment here if the encounter the stability issue.

We can retest these issues at a later date and close them out. 

<img width="1439" alt="Screen Shot 2020-05-14 at 12 01 16 PM" src="https://user-images.githubusercontent.com/49165468/81959898-2688cf80-95de-11ea-9f8b-361e85a22ee5.png">

**Comment by aulneau** [comment]
This was actually another issue that is fixed with: https://github.com/blockstack/explorer/pull/115/commits/559bf3f70b2e3fa1c931e5753eb79109fbfe116e#diff-d5012cfc1638b828bd900111b54bb6adR64

**Comment by aulneau** [comment]
Resolved, closing
