### ISSUE TITLE
Console log error Error: <svg> attribute height: Expected length, "unset".

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#125]
Console error in the chrome browser when successfully selecting a recent transaction from the search dropdown.

The transaction page loads without issue and this seems to work fine. 
But there is a console error that complains about the height.

Error: <svg> attribute height: Expected length, "unset".

<img width="1432" alt="Screen Shot 2020-05-14 at 3 58 11 PM" src="https://user-images.githubusercontent.com/49165468/81980048-ef291b80-95fb-11ea-94b3-49feee267947.png">

**Comment by aulneau** [comment]
This is an issue in the ui library, which will be resolved soon.

**Comment by aulneau** [comment]
will be resolved with https://github.com/blockstack/ux/pull/393
