### ISSUE TITLE
Mobile Cosmetic issue - Token transfer blue label is off center on mobile

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#128]
This only seems to happen in the searchbox on the transaction details page.

Mobile Cosmetic issue - The Token transfer blue label off center in the mobile chrome browser

![Screenshot_20200515-094922_Chrome](https://user-images.githubusercontent.com/49165468/82057657-afad0e80-9691-11ea-8ac5-e4630fb905fa.jpg)

**Comment by timstackblock** [comment]
Also on contract creation 

![Screenshot_20200515-095602_Chrome](https://user-images.githubusercontent.com/49165468/82058502-d61f7980-9692-11ea-9c55-aae654b24eed.jpg)

**Comment by aulneau** [comment]
This has been resolved
