### ISSUE TITLE
Mobile cosmetic issue - STX amount & STX Address overlap on Post conditions section

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#129]
Mobile cosmetic issue 
Chrome 
Android

On the transaction details page for a contract creation transaction scroll to the bottom and view the post conditions section.

You will notice the STX amount & STX Address overlap on Post conditions section also we may want to adjust the links at at the bottom on mobile.

![scrren](https://user-images.githubusercontent.com/49165468/82059456-103d4b00-9694-11ea-8ca0-6a8e2ee0b959.png)

**Comment by aulneau** [comment]
This has been resolved
