### ISSUE TITLE
Add flag for canonical tx 

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#130]

**Comment by agraebe** [comment]
As per discussion, @diwakergupta will help with messaging for this issue 🙏

**Comment by diwakergupta** [comment]
@aulneau is there any more context (e.g. Figma / wireframe) of what we're trying to build so I can draft the copy accordingly?

At a high-level: like many blockchains, the Stacks blockchain can fork. The "canonical" chain is, in our case, is basically the longest chain of confirmed blocks (more details are in [SIP-001](https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-001-burn-election.md)). And so a canonical transaction is a transaction that is included in a valid block on the canonical chain.

Conversely, a non-canonical transaction is a valid transaction that was processed and included in a block on a _non-canonical_ fork.

Does this help?

**Comment by aulneau** [comment]
Will be resolved with https://github.com/blockstack/explorer/pull/232
