### ISSUE TITLE
Improve OG meta data

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#136]
**Describe the bug**
Meta data for twitter does not include the blockstack logo

Transaction ID: Use any transaction 
Address: use any STX address 
Block#  n/a
Time stamp n/a

**To Reproduce**
1. Go to explorer generate a transaction
2. Copy and paste the link in twitter
3. When you post the link you will see an empty box where the blockstack logo should display

**Expected behavior**
The links should display the blockstack logo like the old explorer

**Screenshots**

<img width="604" alt="Screen Shot 2020-05-17 at 1 13 28 PM" src="https://user-images.githubusercontent.com/49165468/82155280-c8f4bd00-9841-11ea-99be-3bf2d6cbcff0.png">

**Comment by timstackblock** [comment]
Same thing for FB the link doesnt show the image link slack

**Comment by agraebe** [comment]
Looks like we're not setting the image props: https://github.com/blockstack/explorer/blob/592720f6b0e494f0161798b446f03f158ddcec46/src/components/meta-head.tsx#L38
