### ISSUE TITLE
Memo field shows extra characters in Browsers Chrome V81 & Edge V81 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#139]
**Describe the bug**
This issue is only on a windows machine, If you go to the transaction details page and look in the memo field you will see  extra characters where there should be empty space. This only happens on a windows machine and not in a Mac for Browsers Chrome V81 & Edge V81 Microsoft 10 OS
 
Link to transaction: https://explorer-git-feat-contract-call-debug.blockstackpbc1.now.sh/txid/0x8982abdd11df77152de15c50b9f52689eb2546cdf66bd4311f26b64389756830

Transaction ID 0x8982abdd11df77152de15c50b9f52689eb2546cdf66bd4311f26b64389756830
Address STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6
Block#  21527
Time stamp 3 days ago

**To Reproduce**
1. Go to on a windows 10 PC open Chrome 81 and also Edge 81
2. Click on the link I listed above
3. Scroll down to the memo page
4. See the error below

**Expected behavior**
The memo field on the transaction details page should appear on a windows machine the same way as it appears below in the image from the mac machine.

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
<img width="1438" alt="Screen Shot 2020-05-18 at 9 28 31 AM" src="https://user-images.githubusercontent.com/49165468/82218605-23e1ef00-98ea-11ea-9175-263ae9fb2a79.png">

<img width="980" alt="Screen Shot 2020-05-18 at 9 14 53 AM" src="https://user-images.githubusercontent.com/49165468/82218620-29d7d000-98ea-11ea-88e1-f3e4ce094e38.png">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 81 & Edge 81

**Comment by aulneau** [comment]
closing in favor of https://github.com/blockstack/explorer/issues/123
