### ISSUE TITLE
Random TX button serves same transaction over and over again

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#140]
THIS MAY NOT BE A BUG AND MAYBE A DATA ISSUE

**Describe the bug**
Today when using the random TX button I noticed that it just served the same TX over and over again. I have seen it work correctly without issue so this may be a stability issue. I wanted to create this ticket  as a place holder to discuss the problem as this may not be a bug and more of a data issue.

This happens in all browsers and OS.

VIDEO OF THE ISSUE
https://screencast-o-matic.com/watch/cYhFIPkurB

**Comment by aulneau** [comment]
This is a data issue -- the sidecar is currently frozen and due to the tx you're seeing being the only one that is of a non-coinbase type, it will always show up.

**Comment by timstackblock** [comment]
Thans @aulneau

**Comment by aulneau** [comment]
The random tx button no longer exists, closing
