### ISSUE TITLE
Add feedback tool

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#141]
**Describe the solution you'd like**
We discussed in the scoping meeting that a feedback tool in the Explorer would be very beneficial. It could help to scope future releases with real user data.

I think we can start with something low effort, like a link to a typeform or Google Forms. Maybe we could just have a floating button in the bottom right corner that opens up the form on a new page?

**Additional context**
See [Explorer 2.0 Working Doc](https://paper.dropbox.com/doc/Explorer-2.0-Working-Document--A0MJIzvMett8edbKndibZ4UqAg-MRJCbgrfR1FXJlrF7FZrH#:uid=732317880672754677080015&h2=Next-Release)

**Comment by aulneau** [comment]
It'd be nice to use a blockstack app for this. cc @xanbots

**Comment by agraebe** [comment]
Ohh, that's a great idea. I'm aware of https://blocksurvey.org/

**Comment by kyranjamie** [comment]
Anything that requires users to already be involved with Blockstack, such as having an account, leaves us foul of selection bias.

**Comment by aulneau** [comment]
@markmhx would be curious as to what you think about using a blockstack app to gather feedback vs something outside of the ecosystem.

**Comment by aulneau** [comment]
@kyranjamie also from my understanding, folks would be using blocksurvey in the same way they'd use any survey tool. They don't have to log in or be involved with blockstack at all.

**Comment by kyranjamie** [comment]
Yeah I said this under the impression you have to sign in with Blockstack— they don't have a demo on their homepage 🤷‍♂️. If that's not the case then, I'm all for it.

**Comment by markmhx** [comment]
I've used BlockSurvey a few times and it's solid. Respondents don't need to authenticate with Blockstack, just survey creators. I'd be in favor of using it instead of a non-Blockstack solution, if only since it's always useful to dogfood.

**Comment by agraebe** [comment]
@aulneau here's the survey: https://blocksurvey.io/survey/1Pb7eeibpfM98hRKBfMUULYCh9BivxE86q/1128356d-4048-48ca-a456-052ef8c5526e

I can actually make a PR - they have a widget generator that we could probably use :)

**Comment by aulneau** [comment]
@agraebe thank you! I think just adding a link in the footer would be ideal. Maybe avoid having a widget being added.

**Comment by agraebe** [comment]
makes sense! Let me know if you need anything else from me for this issue
