### ISSUE TITLE
Auto-refresh pending transaction view

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#143]
**Describe the solution you'd like**
Auto-refresh the view to always display the most recent transaction status. This would improve UX when adding links to developer tools (clicking on a new tx generated a few seconds ago would not fail).

**Additional context**
See [Explorer 2.0 working doc](https://paper.dropbox.com/doc/Explorer-2.0-Working-Document--A0MJIzvMett8edbKndibZ4UqAg-MRJCbgrfR1FXJlrF7FZrH#:uid=732317880672754677080015&h2=Next-Release)

**Comment by aulneau** [comment]
Pending transactions will automatically be available via the sidecar / core node. The only work to be done in the explorer would be to auto refresh the page on a transaction that as a `tx_status` of `pending`

**Comment by agraebe** [comment]
Thanks for the note and let me update the description to account for that

**Comment by agraebe** [comment]
Also noting that this is dependent on: https://github.com/blockstack/stacks-blockchain/issues/1547

**Comment by aulneau** [comment]
This has been implemented
