### ISSUE TITLE
Search by and view STX address

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#144]
**Describe the solution you'd like**
Enable searching and displaying STX address details (balance and transactions).

Potential (but not verified) jobs to be done:
- Contract developers: Review Faucet token transfer was successful
- Contract developers: Ensure the amount of tokens is enough for contract deploys and calls
- Contract developers: Review past contract creations to keep track of contract versions
- Contract developers: Review balance after contract calls
- Token holders: Double-check account balance and share with PBC support
- PBC support: Verifying public account details like balance (not possible through Wallet)

@aulneau would we need designs for the view?

**Describe alternatives you've considered**
An alternative would be to instruct developers to use our wallet. This comes with the following challenges:
- Developers need to have an STX address with tokens. They will use a Faucet and verify the amount accessible to them (initially and potentially throughout the development process). Developers could use the Explorer Sandbox features to obtain STX addresses and tokens, but verifying the amount available would require using and logging into another tool

We could also not add this feature. However, it is argued (but not verified) that looking up STX addresses is a core feature of an Explorer. The Explorer is trusted to display the source of truth of the blockchain. Wallet users might even want to go to the Explorer to cross-check details

**Additional context**
See [Explorer 2.0 working doc](https://paper.dropbox.com/doc/Explorer-2.0-Working-Document--A0MJIzvMett8edbKndibZ4UqAg-MRJCbgrfR1FXJlrF7FZrH#:uid=732317880672754677080015&h2=Next-Release).

**Comment by aulneau** [comment]
related: https://github.com/blockstack/stacks-blockchain-sidecar/issues/113
