### ISSUE TITLE
Clicking the faucet button multiple times creates new boxes with the same transaction# but transaction doesn't load

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#146]
**Describe the bug**
Today when I go to the faucet in the explorer sandbox and click the send STX button multiple times it will appear to create a new transaction but it does not. A new box will have the same transaction number appears and this transaction never loads. 

 This seems to be a new issue, was there a recent change that caused this?

Transaction ID 0xe227333dd1e892cf26e6e236920d5736fbfb2769031053ba52fdc35d1ac25202
Address STSK33PW2N62S8DK5ZJ28XJ25MVYFCBXRX5D5BWS
Block#  DETAILS PAGE DID NOT LOAD
Time stamp  DETAILS PAGE DID NOT LOAD

**To Reproduce**
1. Go to the sandbox on the new explorer and submit a transaction to send STX to the address that is preloaded
2. Click the button multiple times and a new transaction will continue to be created
3. The new transaction never loads and the same transaction is created multiple times

**Expected behavior**
Previously the new transaction loaded in around 60 seconds and multiple transactions were created a new transaction every time the user clicks the send STX button

**Screenshots**
<img width="1433" alt="Screen Shot 2020-05-19 at 9 51 36 AM" src="https://user-images.githubusercontent.com/49165468/82334969-acc65c80-99b6-11ea-8101-8a936c504d45.png">

<img width="1439" alt="Screen Shot 2020-05-19 at 9 59 08 AM" src="https://user-images.githubusercontent.com/49165468/82335482-66253200-99b7-11ea-8dd8-e31d5e746248.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS 10.14.4]
 - Browser [e.g. chrome]

**Comment by timstackblock** [comment]
I have seen this work correctly so I have tagged this with instability as this appears to be a 404 error with 
https://sidecar.staging.blockstack.xyz/sidecar/v1/tx/0xe227333dd1e892cf26e6e236920d5736fbfb2769031053ba52fdc35d1ac25202

<img width="1434" alt="Screen Shot 2020-05-19 at 10 08 16 AM" src="https://user-images.githubusercontent.com/49165468/82336528-b51f9700-99b8-11ea-9307-32f4480da803.png">

**Comment by aulneau** [comment]
I would not say this is a blocking bug -- but something we should account for, for sure.

The reason this happens is a couple things:
- the testnet/mocknet isn't working right now
- transactions take some time to go through, and on the client we aren't keeping track of something called a `nonce` where it's basically a counter that shows how many transactions an address has sent. Normally you can sometimes rely on the network/tooling we are using to increment the nonce automatically, but in this case we should be keeping track of local transactions.

> I have seen this work correctly so I have tagged this with instability as this appears to be a 404 error with
https://sidecar.staging.blockstack.xyz/sidecar/v1/tx/0xe227333dd1e892cf26e6e236920d5736fbfb2769031053ba52fdc35d1ac25202

Transactions will 404 when they have not processed yet.

**Comment by aulneau** [comment]
Tracking here -> https://github.com/blockstack/explorer/issues/147
