### ISSUE TITLE
Can I delete the STX address that the sandbox generates and generate a new one?

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#153]
**Please review the existing enhancement issues at the link below before creating a new one to ensure you do not create a duplicate request.** 
If you see an [existing enhancement issues](https://github.com/blockstack/explorer/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) please comment on the issue or upvote the issue with a :thumbsup:

**Is your feature request related to a problem? Please describe.**
Can I delete the STX address that the sandbox generates and generate a new one?

<img width="308" alt="Screen Shot 2020-05-19 at 11 24 35 AM" src="https://user-images.githubusercontent.com/49165468/82345511-590e4000-99c3-11ea-8337-2ed6b8771c95.png">

<img width="1437" alt="Screen Shot 2020-05-19 at 11 24 31 AM" src="https://user-images.githubusercontent.com/49165468/82345533-60354e00-99c3-11ea-84e3-c56358cbbeab.png">

**Describe the solution you'd like**
Would I be able to still see the button to generate a new address?

**Describe alternatives you've considered**
Is there a button to remove this address?

**Additional context**
This may just be weird functionality I am seeing on testnet, please let me know if this is a testnet issue only, and this works better on mocknet.

**Comment by aulneau** [comment]
This feature is not implemented and not planned for. Ultimately the sandbox will use blockstack for the address etc. So it would all be handled there. I'm going to close this ticket for now.
