### ISSUE TITLE
Transaction details search box drop down does not show Random TX

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#159]
**Describe the bug**
When I select random transaction and view 5 new transactions the recently viewed transaction dropdown on the transaction details page does not update with those transactions. I have to go to the home page and click the recently viewed transactions on the homepage drop down first. Then when I go back to the transaction details I see the transactions in the dropdown. I have included a video of this issue.

Transaction ID n/a
Address n/a
Block#  n/a
Time stamp n/a

**To Reproduce**
1. Go to https://explorer-git-feat-sandboxcontract-call.blockstackpbc1.now.sh/ click the Random TX link at the bottom of the page
2. When you go to the transaction details page of that new random transaction, continue to click that link and generate 10 random tx 
3. Go to the recently viewed transaction dropdown and notice that those transaction are not in the dropdown 
4. Go to the home page and click the recently viewed transactions and you will see the trans actions there.

**Expected behavior**
I am not sure if going to the new page does a page refresh and makes the drop down update with the new transactions but this doesnt appear on the trans action details page the same way it does on the home page.

**Screenshots**
VIDEO OF ISSUE
http://somup.com/cYhro4jpy4

**Comment by aulneau** [comment]
This has been resolved
