### ISSUE TITLE
contract generated in the sandbox cannot be viewed

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#160]
**Describe the bug**
I created contract ST045GZYQXAJY13B7SHV9YRREAK08MFPPM81M18Q.hello-world-contract via the sandbox and it cannot be viewed. It has been about 10 minutes and I cannot view the contract. I think it may be because there is already a hello world contract at that address.

I get the error messafge 
Transaction not found
There is no current record of a transaction containing a contract named: ST045GZYQXAJY13B7SHV9YRREAK08MFPPM81M18Q.hello-world-contract
Transactions can take 60 or more seconds to confirm. If the you know the transaction was sent recently, feel free to refresh.

What happens if a user attempts to create multiple hello-world-contracts and the same address Transaction ID ST045GZYQXAJY13B7SHV9YRREAK08MFPPM81M18Q.hello-world-contract

<img width="1415" alt="Screen Shot 2020-05-21 at 12 13 59 PM" src="https://user-images.githubusercontent.com/49165468/82580001-965a0580-9b5c-11ea-8107-a82f79213000.png">

**Comment by aulneau** [comment]
I believe this was due to issues wrt the node/sidecar and has since been resolved.
