### ISSUE TITLE
Deployment checklist requires GA tags

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#163]
**Please review the existing enhancement issues at the link below before creating a new one to ensure you do not create a duplicate request.** 
If you see an [existing enhancement issues](https://github.com/blockstack/explorer/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) please comment on the issue or upvote the issue with a :thumbsup:

**Is your feature request related to a problem? Please describe.**
Install GA tags in the new explorer per checklist.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Do we want to continue to use GA tags?

**Additional context**
<img width="1431" alt="Screen Shot 2020-05-26 at 10 01 24 AM" src="https://user-images.githubusercontent.com/49165468/82910009-0c34e700-9f38-11ea-85eb-e12ca9d4675e.png">

**Comment by aulneau** [comment]
The checklist should be updated, we don't use Google analytics anymore, we use fathom (which is implemented already). Closing this.
