### ISSUE TITLE
Sandbox: After keychain generation, run faucet call right away

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#169]
**Is your feature request related to a problem? Please describe.**
When using the sandbox, every developer getting started would likely need to run the faucet call. 

**Describe the solution you'd like**
Why don't we run it automatically after the keychain was generated? What harm would it do, if any?

**Comment by aulneau** [comment]
This will likely be handled with the implementation of passing all that responsibility to the authenticator. Might not make sense to implement it now as it will be replaced soon.

**Comment by agraebe** [comment]
I see. It makes sense to me!

**Comment by aulneau** [comment]
But def good idea! I do want this functionality to exist somewhere.
