### ISSUE TITLE
Two keychains generated on signup

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#174]
**Describe the bug**
When I first sign up, I seem to get 2 keychains:
<img width="1429" alt="Screen Shot 2020-05-28 at 12 53 50 PM" src="https://user-images.githubusercontent.com/1671228/83187200-a173df00-a0e2-11ea-88c6-a44ce8b0a18e.png">

**To Reproduce**
1. Open the Sandbox in an incognito tab
2. Create a new account through Connect
3. See two keychain notifications

**Expected behavior**
Only one keychain should be generated.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome

**Comment by aulneau** [comment]
This has been resolved
