### ISSUE TITLE
Connecting to sidecar fails due to CORS

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#189]
**Describe the bug**
Calling https://testnet-explorer.blockstack.org/transactions
results in
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sidecar.staging.blockstack.xyz/sidecar/v1/tx?type%5B…type%5B%5D=contract_call&type%5B%5D=token_transfer&limit=200. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
```

**Comment by aulneau** [comment]
This sometimes happens when the node/sidecar has stalled or failed, and has yet to be reset. I am going to close this out now as I have not been able to recreate this issue. If it persists, please feel free to reopen this ticket.
