### ISSUE TITLE
Confirmation time displays "NaN years ago" in sandbox

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#191]
**Describe the bug**
Send stacks to an address and when the pop up displays the transaction ID it all show Confirmation time displays "NaN years ago" in sandbox

Transaction ID 0x35eaf218ad1561a15a6055aeb13d28ba3e965fe23bc6657201c764cb0fb67f21
Address STK0RK9Z7RV289CT6JVBV79HN4J34WNGWMZDZ4VY
Block#  **_not recorded_**
Time stamp **_not recorded_**

**To Reproduce**
1. Go to send tokens from the the faucet
3. Scroll down you will notice the pop up has NaN years ago
4. click the link and you will notice there is a Nan years ago on the transaction

**Expected behavior**
I expected to see a valid block height and confirmation number

**Screenshots**

<img width="604" alt="Screen Shot 2020-06-12 at 8 45 35 AM" src="https://user-images.githubusercontent.com/49165468/84503980-2d603c00-ac89-11ea-8fbb-559d12c633c6.png">

<img width="1405" alt="Screen Shot 2020-06-12 at 8 49 46 AM" src="https://user-images.githubusercontent.com/49165468/84504328-c0997180-ac89-11ea-98b2-5290a11809b0.png">

:

**Comment by aulneau** [comment]
This has been resolved.
