### ISSUE TITLE
the transactions is always in pending state, can't receive the fund.

### ISSUE THREAD

**Issue by harsh-98** [blockstack/explorer#192]
**Describe the bug**
I requested funds from faucet , but the transaction is not completing, saying `This transaction would have succeeded, but was rolled back by a supplied post-condition.`

Transaction ID  0xa4a95cc993b5028ce79dd67be084375cfe27f677945a72eb6fc15cb6f9467c76
Address ST1R80B269Z26EJDF1EPC80WH6AFE6ATXE6YBEDZ1 
Block#  
Time stamp

**Expected behavior**
Funds should be transferred within 2mins.

**Screenshot**
<img width="853" alt="Screenshot 2020-06-22 at 6 53 52 PM" src="https://user-images.githubusercontent.com/23700929/85292612-cda03700-b4b9-11ea-9da3-5732d02fe015.png">

**Comment by aulneau** [comment]
Hi @harsh-98, thanks for the issue! This should be fixed and live on https://testnet-explorer.blockstack.org.
