### ISSUE TITLE
I get the PreconditionFailedError message below on the faucet 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#193]
**Describe the bug**
I get the error message below on the faucet page of the sandbox after login in with connect

This occurs with pull request 190 using the link below
 https://explorer-git-feat-release-fixes.blockstackpbc1.vercel.app/

```Error when uploading to Gaia hub. If you believe this exception is caused by a bug in blockstack.js, please file a bug report: https://github.com/blockstack/blockstack.js/issues Error Code: precondition_failed_errorStack Trace: Error at Object.<anonymous> (https://explorer-git-feat-release-fixes.blockstackpbc1.vercel.app/_next/static/OlqNxFFcBfk8n6IU2zWlr/pages/sandbox.module.js:1:258451) at Generator.next (<anonymous>) at s (https://explorer-git-feat-release-fixes.blockstackpbc1.vercel.app/_next/static/OlqNxFFcBfk8n6IU2zWlr/pages/sandbox.module.js:1:246546)
```

**To Reproduce**
1. Go to  https://explorer-git-feat-release-fixes.blockstackpbc1.vercel.app/ when testing pull 190
2. Click on sandbox
3. Login with blockstack connect
4. See error on the faucet page

**Expected behavior**
The faucet page should display without the error message

**Screenshots**

<img width="1440" alt="Screen Shot 2020-06-22 at 2 25 51 PM" src="https://user-images.githubusercontent.com/49165468/85322760-d599b000-b494-11ea-84ed-c11962ee546a.png">

<img width="1439" alt="Screen Shot 2020-06-22 at 2 30 21 PM" src="https://user-images.githubusercontent.com/49165468/85322834-ef3af780-b494-11ea-850b-139eabf3d787.png">

**Comment by aulneau** [comment]
this should be resolved with https://github.com/blockstack/explorer/commit/a2f77aabea4c9affb4c3e9c6a70e8153cc2e2d63

**Comment by timstackblock** [comment]
ok thanks
