### ISSUE TITLE
tried to deploy a contract

### ISSUE THREAD

**Issue by RomaneGreen** [blockstack/explorer#196]
Got an issue error

"Whoops! something went wrong
An error occurred on the client. Please feel free to file an issue and describe: what you were attempting to do, the URL you are trying, and anything that is in the console."

<img width="1440" alt="Screen Shot 2020-07-05 at 1 34 08 PM" src="https://user-images.githubusercontent.com/19755484/86538478-3d53f000-bec4-11ea-9b8f-a6d4f6465eae.png">

**Comment by agraebe** [comment]
this was due to a testnet downtime and should be resolved.
