### ISSUE TITLE
Show estimate for tx completion

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#202]
With an endpoint to get the block time (https://github.com/blockstack/stacks-blockchain-sidecar/issues/171), we can indicate roughly how long one would have to wait before a transaction is completed

**Comment by agraebe** [comment]
FYI, the PR on the API for this: https://github.com/blockstack/stacks-blockchain-api/pull/199

**Comment by aulneau** [comment]
closing in favor of: https://github.com/blockstack/explorer/issues/261
