### ISSUE TITLE
Server error 500 on calling the faucet due to ConflictingNonceInMempool

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#218]
**Describe the bug**
When I ask the faucet for two different addresses, I get an error 500

Error: Response 400: Bad Request fetching http://stacks-node-follower.staging-argon.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"2e4cff86d2d4bf138e6b404f0adc717dc0ccd3bc588fa291e6d64f2fb788c3fa"}    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:73:19)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:52:30)    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:104:24)    at async /app/lib/api/routes/faucets.js:98:30    at async run (/app/node_modules/p-queue/dist/index.js:255:29)

**To Reproduce**
1. Go to faucet
1. enter stx address
1. click request stx
1. enter another address
1. click request stx
1. see error

**Expected behavior**
An error message that this is a temporary issue

**Screenshots**
Error: Response 400: Bad Request fetching http://stacks-node-follower.staging-argon.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"2e4cff86d2d4bf138e6b404f0adc717dc0ccd3bc588fa291e6d64f2fb788c3fa"}    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:73:19)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:97:5)    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:52:30)    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:104:24)    at async /app/lib/api/routes/faucets.js:98:30    at async run (/app/node_modules/p-queue/dist/index.js:255:29)

**Desktop (please complete the following information):**
 - Browser firefox

**Additional context**
#147 could be related

**Comment by aulneau** [comment]
Interesting. I am not sure why it would do that with two different addresses. I'll have to look into this further. I wonder if this could be further up in the stream, @zone117x what do you think? (meaning, is this an issue with the faucet itself?)

**Comment by psq** [comment]
@aulneau this error is most likely due to the fact that there is already a transaction in the mempool for the same address and same nonce, but the nonce is incorrect, so it wont' get mined, so the transaction will stay in the mempool for 256 blocks (or so) till it gets garbaged collected.
