### ISSUE TITLE
Question: What PoX-related updates should the next release include?

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#221]
Same as [the ticket in the Stacks API repo](https://github.com/blockstack/stacks-blockchain-api/issues/190), let's identify updates we would like to make in the Explorer.

@aulneau do you have any initial thoughts?

**Comment by agraebe** [comment]
the [progress is tracked in a paper doc](https://paper.dropbox.com/doc/PoX-features-in-the-Explorer-2.0--A5YTca~nfLvFPBh~vORuszDQAQ-WubrHOqycreAVwvya9KGX). I'll also see if I can get some user feedback on that topic.

**Comment by agraebe** [comment]
Seems like `Liquid STX Supply` would be of interest

**Comment by Trudko** [comment]
@agraebe what about amount of Bitcoin committed by a winning miner of a block?

**Comment by aulneau** [comment]
Closing in favor of these issues:
https://github.com/blockstack/explorer/issues/321
https://github.com/blockstack/explorer/issues/297
