### ISSUE TITLE
Display amount on transaction page while pending

### ISSUE THREAD

**Issue by markmhx** [blockstack/explorer#223]
When a transaction is still pending, there's no way to see the amount sent, only the fee. After confirmation, this value is shown only in the "event log". I expected this value in the top section's table both before and after confirmation.

## Before confirmation

<img width="1261" alt="Screen Shot 2020-08-10 at 17 41 47" src="https://user-images.githubusercontent.com/28991/89802023-322e5880-db31-11ea-9eb3-e16962130d7f.png">

## After

<img width="1262" alt="Screen Shot 2020-08-10 at 17 42 23" src="https://user-images.githubusercontent.com/28991/89802031-35294900-db31-11ea-9cb2-7ad125411b7b.png">

**Comment by aulneau** [comment]
@zone117x is it possible to see the value of STX sent in a pending tx?

**Comment by zone117x** [comment]
Yes, pending stx txs show amount. Looking at one in the mempool right now:
https://stacks-node-api.blockstack.org/extended/v1/tx/0xc43ef5c6f0af002540c99259cf38c82f8d9c91c3d027f8e61df7f0d7c4d36ab1
```json
{
"tx_id": "0xc43ef5c6f0af002540c99259cf38c82f8d9c91c3d027f8e61df7f0d7c4d36ab1",
"tx_type": "token_transfer",
"fee_rate": "180",
"sender_address": "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6",
"sponsored": false,
"post_condition_mode": "deny",
"tx_status": "pending",
"receipt_time": 1603205374,
"receipt_time_iso": "2020-10-20T14:49:34.000Z",
"token_transfer": {
  "recipient_address": "ST20EBB2PHSKC7DQQT4AT8QSWGWKMCXRNB09Q48DK",
  "amount": "500000000",
  "memo": "0x46617563657400000000000000000000000000000000000000000000000000000000"
},
"events": []
}
```
