### ISSUE TITLE
Design: STX unlocking view

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#224]
The old explorer has a view for [STX unlocking](https://explorer.blockstack.org/address/stacks/SP3Y23TNRCV7H0XSC2F0VYZX9XM56BND00C99M31R). We should have a minimal version of that available in the new Explorer, on the address view. The following information seems relevant:
- [ ] # of locked STX
- [ ] # of unlocked STX
- [ ] # of STX unlocked/per period
- [ ] date when 100% of STX is unlocked

Relate to other Explorer mainnet release design tasks, this seems high in priority.

**Comment by jasperjansz** [comment]
@aulneau are you picking this up for dev or do you think there should be design changes? If the latter, please comment

**Comment by aulneau** [comment]
I moved this because I don't have an ability to implement this, as none of this data is available.

**Comment by agraebe** [comment]
@zone117x do you have input for this? should we create a ticket to track work on the api?

**Comment by aulneau** [comment]
This has been implemented
