### ISSUE TITLE
Design: BTC details in existing views

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#225]
Developer testing indicated that there is interest in the BTC relationship of PoX. Developers would like to see how our blockchain relates to BTC. In order to display that relationship more prominently, we should extend our existing views and display:
- [ ] BTC transaction associated with a Stacks 2.0 transaction
- [ ] BTC block associated with a Stacks 2.0 block

Compared to other Explorer mainnet release design tasks, this seems to be high priority

**Comment by jasperjansz** [comment]
@aulneau are you picking this up for dev or do you think there should be design changes? If the latter, please comment

**Comment by aulneau** [comment]
@zone117x what kind of data will be exposed for this? Currently I am not aware of any underlying btc data (esp due to us being on testnet). 

@jasperjansz I don't think I can implement this yet as the data isn't available afaik

**Comment by zone117x** [comment]
Reference issue: https://github.com/blockstack/stacks-blockchain/issues/1950
