### ISSUE TITLE
Design: Testnet status view

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#226]
We would like to include the [status checker](http://status.test-blockstack.com/) into the new Explorer. The goal is to quickly show if/how operational the testnet.

I would suggest to include such a view outside of the sandbox because of relevance for anyone (not only developers).

Compared to other Explorer mainnet release design tasks, this seems a high priority.

**Comment by jasperjansz** [comment]
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=1882%3A18434
