### ISSUE TITLE
Design: Contracts called

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#228]
To show the unique strength of Clarity, we should show what other contracts a contract would call during execution. I believe we have designs for code lines executed but we don't seem to have a list of other contracts.

Compared to other Explorer mainnet release design tasks, this seems to be a medium priority.

**Comment by jasperjansz** [comment]
@aulneau are you picking this up for dev or do you think there should be design changes? If the latter, please comment

**Comment by aulneau** [comment]
@jasperjansz I don't believe this is currently possible from data exposed via the api. cc @zone117x

**Comment by zone117x** [comment]
This would require something _similar_ to this https://github.com/blockstack/stacks-blockchain/issues/1185

Seems pretty far away at the moment

**Comment by agraebe** [comment]
moving this to the icebox so we can get back to it once we're closer to the data avilability
