### ISSUE TITLE
Design: Miner power graph

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#229]
The blockchain team expressed the need for a miner power graph to be able to demonstrate how decentralized our network is. The miner power data would come from annotations inside Coinbase transactions (from the last 24 hours' worth of blocks).

Compared to other Explorer mainnet design tasks, this seems lower in priority.

Examples:
    - https://www.blockchain.com/charts/hash-rate
    - https://www.blockchain.com/charts/pools
    - https://www.etherchain.org/charts/topMiners

**Comment by jasperjansz** [comment]
https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=1882%3A18930
