### ISSUE TITLE
Sandbox should use the stx address from the user's profile

### ISSUE THREAD

**Issue by njordhov** [blockstack/explorer#231]
**Describe the bug**

The stx address used in the Sandbox is different than the stx address associated with the user's profile. This negatively affects the experience for users of apps that deploy contracts on testnet, as the Sandbox will show mismatching information.

A response to #173 notes that this behavior is _not a bug_  - but it's clearly not a feature either... Per May 28, the status was that _eventually we will have the sandbox use the seed phrase address from connect, but that is still WIP._ 

**Expected behavior**

The Sandbox should display and use the same stx address as associated with the user's profile, instead of the one in `identity`. It is already available to Explorer through the `userSession` object in the `profile` of the `userData`.

**Additional context**

Related discussion in the Support channel: https://discordapp.com/channels/621759717756370964/625538774230892545/747260388617224282

**Comment by dantrevino** [comment]
This would be a huge aid in my testing.  Otherwise whatever I try in the sandbox cannot be directly verified anywhere else, unless we open up the code and generate an address in exactly the same way.

We have an address in the profile, it'd be a big help to be able to use it.
