### ISSUE TITLE
Provide debug information for developers

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#233]
**Is your feature request related to a problem? Please describe.**
Some of my contract deployment calls, as well as contract function calls fail. As a developer it is difficult to understand why and how to get more information about the failed transaction.

**Describe the solution you'd like**
The explorer should a button for failed transactions that directs developers to more information.

**Describe alternatives you've considered**
Running my own node, enable debug mode and scroll through millions of lines..

**Additional context**
E.g. https://testnet-explorer.blockstack.org/txid/0x89c1d25d16abdf4f7d0f24fd632135a961ae021475b0a4881cf3ef2bd7b1ffa2
https://sidecar.staging.blockstack.xyz/sidecar/v1/tx/0x89c1d25d16abdf4f7d0f24fd632135a961ae021475b0a4881cf3ef2bd7b1ffa2

**Comment by aulneau** [comment]
This is a great idea, but I think this would be an issue for either the stacks blockchain api or core itself. @zone117x what do you think?

**Comment by aulneau** [comment]
Closing this as this is not an explorer related bug/feature

**Comment by friedger** [comment]
A first step would be to show the transaction result, no need to change the core code.

**Comment by aulneau** [comment]
> A first step would be to show the transaction result, no need to change the core code.

This is implemented by #265
