### ISSUE TITLE
[Sandbox] Support deep link to a contract call

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#234]
**Is your feature request related to a problem? Please describe.**
To share a contract with other users, currently, you have to provide a lengthy description how to open the sandbox and search for the contract with address and name. 

**Describe the solution you'd like**
It would be much easier to just share a link like
```
https://testnet-explorer.blockstack.org/sandbox?tab=contract-call&contract=ST12...monsters
```
Maybe even provide parameters for function name and args.

**Describe alternatives you've considered**
Share a description how to search for the contract

**Additional context**

**Comment by agraebe** [comment]
Are you looking for a way to provide users the ability to run the contract?

**Comment by friedger** [comment]
Yes

**Comment by friedger** [comment]
It is also for me to bookmark my contract calls.

**Comment by agraebe** [comment]
I also experienced the issue when looking for the pox contract - can't easily link to it (different deploy tx id upon reset).. I way to link out to a contract would be nice
