### ISSUE TITLE
[TESTNET-BUG] Read-only call fails for "owner-of?" function

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#235]
**Describe the bug**
Function names with "?" are not url encoded when making a contract call in sandbox.

**To Reproduce**
1. Go to https://testnet-explorer.blockstack.org/sandbox?tab=contract-call
1. Search for contract ST25GX7MJA4FGEYYH5E7EBW30BYA4VG4VC1XETXXZ.speedy-monsters
1. Call read-ony function `owner-of?` with monster-id 1
1. See no result. The network monitor shows a call to `owner-of` not `owner-of?` 
```
{"POST":{"scheme":"https","host":"sidecar.staging.blockstack.xyz","filename":"/v2/contracts/call-read/ST25GX7MJA4FGEYYH5E7EBW30BYA4VG4VC1XETXXZ/speedy-monsters/owner-of"}}
```
**Expected behavior**
A call to `owner-of%3F` should be made instead 

```
curl -X POST -k -H 'Content-Type: application/json' -i 'https://sidecar.staging.blockstack.xyz/v2/contracts/call-read/ST25GX7MJA4FGEYYH5E7EBW30BYA4VG4VC1XETXXZ/speedy-monsters/owner-of%3F' --data '{"sender":"ST25GX7MJA4FGEYYH5E7EBW30BYA4VG4VC1XETXXZ","arguments":["0x0100000000000000000000000000000001"]}'
```

**Comment by friedger** [comment]
@timstackblock Is this a testnet bug?

**Comment by timstackblock** [comment]
@friedger That may be explorer bug in the sandbox, @aulneau is the developer working on the explorer he should be able to help.

**Comment by timstackblock** [comment]
@jdbender66  @friedger this is a sidecar issue the functionality will not make it into main net so I do not think this will be a testnet bug.

@diwakergupta please correct me if I am wrong
