### ISSUE TITLE
Provide input on a new iteration of the Explorer

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/explorer#243]
We spoke about how the data is different from what I used in the design, and how this leads to problems implementing the designs. If I know how the data presents I can make another iteration. You can just share screenshots to get the ball rolling.

**Comment by aulneau** [comment]
- [ ] BNS names don't make sense currently on address pages. We might not have a 1-1 relationship with addresses. 
![Screen Shot 2020-10-13 at 3 17 34 PM](https://user-images.githubusercontent.com/11803153/95911570-4546ea00-0d67-11eb-808e-9a733f231a80.png)
