### ISSUE TITLE
traits not handled in contract calls

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#244]
**Describe the bug**
Trait references are not handled in contract calls, e.g. for ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.market (https://testnet-explorer.blockstack.org/txid/0x8fa5abba6f491e0ba7cf0223c8ef15f8e45233f7cef6552c606e92765cefe2c5)

There are two different contracts that implement the `tradble` trait:
* ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.constant-tradables
* ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.monsters

When entering the contract id nothing happens.

**To Reproduce**
1. Go to sandbox -> contract call
2. search for ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.market
3. search for bid function
1. enter `ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.constant-tradables` as trait
1. enter 1 as tradble-id
1. enter 1000 as bid price.
4. See that nothing happens.

**Expected behavior**
An error message should be shown if the arguments were wrong or the transaction should be broadcasted.

**Comment by friedger** [comment]
This is due to https://github.com/blockstack/stacks.js/issues/872
Fixed now

**Comment by aulneau** [comment]
I have updated the dep, and also I think this is related to the stacks wallet extension, closing for now.
