### ISSUE TITLE
Contract not found

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#245]
**Describe the bug**
When clicking on a contract in the search result a message "Transaction not found" is shown

**To Reproduce**
1. Go to 'Contract Call'
1. Search for `ST12EY99GS4YKP0CP2CFW6SEPWQ2CGVRWK5GHKDRV.market`
1. Click on 'View Contract' 

**Expected behavior**
It should open the tx of the contract deployment.

**Screenshots**
![Screenshot from 2020-10-13 08-57-59](https://user-images.githubusercontent.com/1449049/95826192-3bef5a80-0d32-11eb-843f-7b7442317386.png)

**Additional context**
It looks like `ContractCallButton` sends a contractId, but page `[txid].js` does not properly resolve this.

**Comment by psq** [comment]
are you sure the contract was re-deployed successfully after Monday's reset?  Transactions don't see to get processed.
