### ISSUE TITLE
Contract call transactions: Argument list

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#246]
Contract call transactions show a list of arguments. The arguments seem to be decoded incorrectly:

![rKK5gMNg](https://user-images.githubusercontent.com/1671228/95925887-c904d480-0d6f-11eb-8242-50f3b48dcb10.png)

Maybe we could display the argument type (based on the ABI) and format the values in a more readable way?

**Comment by aulneau** [comment]
This is an issue with the sidecar, closing
