### ISSUE TITLE
Underlying btc information

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#249]
We want to display the relationship to BTC on tx pages, but I currently don't know where/when this data will be available. @zone117x can you comment?

![Screen Shot 2020-10-20 at 9 49 16 AM](https://user-images.githubusercontent.com/11803153/96603418-9f8d0100-12b9-11eb-90f3-37fa62afc7b1.png)

**Comment by zone117x** [comment]
See issue https://github.com/blockstack/stacks-blockchain/issues/1950

**Comment by agraebe** [comment]
FYI - a PR is out for this: https://github.com/blockstack/stacks-blockchain/pull/1983. we'd need to do follow up work on the API (including docs)

**Comment by zone117x** [comment]
Reference https://github.com/blockstack/stacks-blockchain-api/issues/302
