### ISSUE TITLE
[Sandbox] Contract calls with string type arguments fail silently

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#251]
**Describe the bug**
Making a contract call to a function with a string-ascii type argument fail silently. Pressing the button does not do anything.

Current example: https://testnet-explorer.blockstack.org/txid/0x74d156494bcec04872a0169e3b371edef5d69e978bd038fd4ab45c790ee42da6

`register` function

**To Reproduce**
1. Go to explorer link above
2. Copy contract address and search for contract in "Contract Call"
3. For `register` enter two strings
4. Click on "Submit"
5. See that nothing happens, no console log, no network call

**Expected behavior**
Broadcast the signed contract call tx

**Additional context**
https://github.com/blockstack/ux/issues/639

**Comment by aulneau** [comment]
This should be fixed, as this is now handled by the extension
