### ISSUE TITLE
Unable to create contract

### ISSUE THREAD

**Issue by agnelvishal** [blockstack/explorer#253]
The following contract create transactions have failed.
1. https://testnet-explorer.blockstack.org/txid/0xa245778830bf1dc7aaa0213f78cc190280d8da7d3dd9ff42ddbe04f1297405d1
2. https://testnet-explorer.blockstack.org/txid/0xec9527bced9fcde0f2569c3ea3efbbd485f9747047d881241b7a48ff38b038c4

What is the reason?

I used the contract deploy in sandbox at https://testnet-explorer.blockstack.org/sandbox?tab=contract-deploy The clarity code was unchanged. Tried repeating few times but got error again.

**Comment by agraebe** [comment]
thanks for submitting this - the testnet was reset since then. what error did you see? do you have the `clar` file for the contract handy?
