### ISSUE TITLE
For the same STX address the balance from CLI is not equal to the balance from the explorer

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#281]
**Describe the bug**
For the same address the balance from CLI is not equal to the balance from the explorer

Address STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6

**To Reproduce**
1. Go to https://testnet-explorer.blockstack.org/address/STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6
2. in the CLI do a blockstack balance STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6 -t
3. View the balance there and you will see a different value

**Expected behavior**
The balance in the explorer should be accurate

**Screenshots**
<img width="1416" alt="Screen Shot 2020-12-01 at 1 53 06 PM" src="https://user-images.githubusercontent.com/49165468/100784245-e56ed600-33dc-11eb-874a-0959b2fdfc01.png">
<img width="1176" alt="Screen Shot 2020-12-01 at 1 52 55 PM" src="https://user-images.githubusercontent.com/49165468/100784247-e7389980-33dc-11eb-9711-722a1513338b.png">

**Comment by zone117x** [comment]
This is a quirk of testnet mode where a handful of addresses (such as the faucet address) are artificially given STX at boot. This won't happen in mainnet, and might be a `won't fix` for now.

**Comment by timstackblock** [comment]
ok closing this out
