### ISSUE TITLE
Redis caching 

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#285]
Since the explorer frontend is a next.js application, that means the application will be rendered on the server as pages are accessed. To help improve performance, we want to cache certain resources that are more static. I've currently got a simple LRU cache set up where we cache the following pages after they have been rendered:

- any non-pending transaction page
- any block page

We are able to pretty confidently say that currently, these two types of pages contain data that will not update over time. The other pages all contain data that will be highly dynamic:
- home
- transactions
- blocks
- address
- sandbox (already only client side)

It's possible that transaction pages that display most recently calls to a contract might need to be removed from this list, but currently that data is not possible.

The advantage of adding some caching layer to the frontend application is that it's pretty CPU intensive to render these pages out, and as such, if we are able to reduce that, we should. With the legacy explorer there were numerous caching related issues where there might have been old data rendered, or broken data generally.

To try and prevent some of that from happening, I suggest we do the following:

- [deterministically generate a next.js build ID](https://github.com/nexdrew/next-build-id) to be used to add to the caching key eg: `${ID}-resource-route`
  - This is helpful because when a new release is deployed, the build ID will change (but be the same between pods), and any resource will never try and fetch an older version. This will prevent issues around if we update styles, js, etc.
- only cache things that are known to be more or less static after their initial render
- use a redis cache because storage-based caching is not as performant, or will not work with how we have multiple instances of the same build

We still need to test this out and see with load-testing if this is something that provides substantial benefit (we should be conducting some tests this week).

**Comment by hstove** [comment]
I would note that most of the cache issues from the current explorer came from the API server. There was more complexity there, as we were caching materialized views of multiple queries that came from multiple different places.

We had a similar caching layer on the front-end, which didn't really have issues. However, we ended up disabling that cache to put Cloudflare in front of it, and serving proper ETags from the front-end server made this work well if I recall correctly. Maybe we should just do that?

**Comment by aulneau** [comment]
@hstove would we be able to cache only specific pages on cloudflare? the issue is we'd need to be able to do them based on the data returned. You can see how I'm doing it currently here https://github.com/blockstack/explorer/blob/master/server/index.js#L33

**Comment by hstove** [comment]
Ah, since you're not caching pending transactions, then it might be tricky. The server can send the proper headers to not cache that page. And you can definitely setup rules for which paths to cache. I'd still probably lean towards CF for caching but I'd like to hear @wileyj 's thoughts - Redis or Cloudflare for caching some pages on the front end?

**Comment by wileyj** [comment]
Cloudflare would absolutely be easier here, but it also makes it trickier on the mgmt side. 
We'd have to add paths/ remove paths more manually vs redis where it can be done in the codebase. 

If the pathnames are going to be relatively simple and not likely to change often, we can give it a shot and see if it'll work. 
@aulneau send us an issue to add some caching with the path(s) you think you'll need and we can see how we like it.

**Comment by aulneau** [comment]
Questions related to cloudflare caching:

- are we able to cache transactions that meet specific criteria -- eg: non-pending txs (using data from the response)
- are we able to clear the cache after a new build?

> caching with the path(s) you think you'll need and we can see how we like it.

There is no URL pattern that would be able to infer a state of a transaction

**Comment by zone117x** [comment]
I don't think we could use path rules for cloudflare caching. It would have to use the ETag response header (or whatever header controls cloudflare caching). 

Also note that along with pending transactions, we should avoid caching any transactions or blocks that are N blocks new. Where N is some reasonable depth in which a fork isn't likely, probably between 20 and 100.
