### ISSUE TITLE
[TESTNET_BUG] Can't transfer funds

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#287]
**Describe the bug**
My account says I have 93m STX. When I try to transfer stacks, the authenticator pops up and shows that I don't have enough funds.

**To Reproduce**
1. Go to 'https://testnet-explorer.blockstack.org/sandbox'
2. Click on 'faucet' to get some STX
3. Wait until tx is confirmed
4. Click on 'send stx' and enter recipient
5. See error NotEnoughFunds

**Expected behavior**
Funds should be transferred

The same account for sending the transaction should be used:
* Testnet explorer uses ST217QA3TCS7Y1K61QWZ9PS2G1TM11CQZKQVGMRMS (app user address)
* Authenticator uses ST2NM3E9MAWWRNGFEKW75QR4XXVA856N4MHNMYA3T (owned user address)

**Screenshots**
![Screenshot from 2020-12-18 08-50-07](https://user-images.githubusercontent.com/1449049/102588628-0db14100-410e-11eb-8a42-a4d6cc8a7780.png)
![Screenshot from 2020-12-18 08-49-41](https://user-images.githubusercontent.com/1449049/102588632-10139b00-410e-11eb-9d66-d6ef59932853.png)

//cc @timstackblock

**Comment by timstackblock** [comment]
Thanks for the issue @friedger but the explorer sandbox does not use the same address as your authenticator login. It creates a new address on the fly I do not think this is a bug. It is the way the sandbox currently works  @aulneau could you chime in here.

**Comment by aulneau** [comment]
> but the explorer sandbox does not use the same address as your authenticator login

This is no longer true, the explorer does use connect and its associated address. The address you see in the sandbox should be exactly the one you see in connect. 

@friedger could you clear your data for the sandbox and authenticate again and see if this error persists?

**Comment by friedger** [comment]
@aulneau Indeed, using a private browser worked. Thank you.
