### ISSUE TITLE
STX total in the V2 explorer for legacy Main-net addresses are not equal to STX total for V1 explorer this should match exactly

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#288]
**Describe the bug**
I am looking at a legacy address that was imported in for stacks V1 and the balance is incorrect in the new explorer butis correct in the new wallet.

Address SP2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK7880556R3

**To Reproduce**
1. Go tohttps://testnet-explorer.blockstack.org/address/SP2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK7880556R3 and compare it to https://explorer.blockstack.org/address/stacks/SP2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK7880556R3
2. Then go in the new wallet and you will see that the address and correct balance is present in the new wallet

**Expected behavior**
The explorer has the address but does not have the correct balance, it should match the legacy explorer the same way the new v2 wallet  matches the balances correctly

**Screenshots**
<img width="1341" alt="Screen Shot 2020-12-21 at 9 44 23 AM" src="https://user-images.githubusercontent.com/49165468/102788909-5f0d3a80-4371-11eb-97e1-b243f9efab37.png">
<img width="1266" alt="Screen Shot 2020-12-21 at 9 35 46 AM" src="https://user-images.githubusercontent.com/49165468/102788913-5fa5d100-4371-11eb-8e70-a0d09de16677.png">
<img width="1041" alt="Screen Shot 2020-12-21 at 9 35 39 AM" src="https://user-images.githubusercontent.com/49165468/102788917-603e6780-4371-11eb-9443-ac9a63e127ae.png">

**Comment by aulneau** [comment]
This is not an issue with the explorer, but with the underlying API. it could be related that you're trying to check a mainnet address but in testnet, you'd need to use the testnet address if you're not already. If you are using the testnet address, this is an issue with the stacks-node-api.

**Comment by zone117x** [comment]
Looks correct when using the correct testnet address: https://testnet-explorer.blockstack.org/address/ST2J0JRNZPYGWG4Y59Q1C6Z1Y87VW3JK78946EYYC
![image](https://user-images.githubusercontent.com/1447546/102877385-f42e3300-4446-11eb-9f90-515d57dce19b.png)
