### ISSUE TITLE
Contract call fails

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#290]
**Describe the bug**
- Navigating to https://testnet-explorer.blockstack.org/sandbox
- clicking on contract call
- Filling out the details with the stacking contract id (ST000000000000000000002AMW42H.pox)

An error is shown: "Something went wrong". Can't see any network calls or specific errors in the console

**Comment by aulneau** [comment]
I see, the issue is the address was hard coded, just need to switch out the address with the one in the network. Eventually when the `/v2` endpoints become more stable, we can fetch the `pox` endpoint and get the address dynamically that way (For working in different networks etc)

**Comment by friedger** [comment]
Is this still an issue?
the pox contract address changes on network change as well.

**Comment by agraebe** [comment]
I just tried it - the issue was resolved but not closed. closing now
