### ISSUE TITLE
Transaction not found

### ISSUE THREAD

**Issue by lgalabru** [blockstack/explorer#292]
I spent some time testing pox recently, and was trying to use the explorer for tracking the transactions.
Noticed 2 bugs:
- the explorer is showing transactions I was looking for (that could be fetched from the api), but was unable to view the details.
- sometime, the `transaction not found` is displayed in the footer.

https://user-images.githubusercontent.com/87777/103790221-ebc12500-500e-11eb-82e7-7d5d79c785bd.mov

**Comment by aulneau** [comment]
https://github.com/blockstack/explorer/pull/289 should resolve this issue. You can try https://explorer-git-feat-more-design-improvements.blockstack.now.sh/

**Comment by aulneau** [comment]
> sometime, the transaction not found is displayed in the footer.

Do you have a screenshot of this?

**Comment by lgalabru** [comment]
Yeah I did capture - it's in that video

**Comment by aulneau** [comment]
> Yeah I did capture - it's in that video

oh yes thank you, that's nuts lol never seen that before :)

**Comment by aulneau** [comment]
These have been resolved
