### ISSUE TITLE
[TESTNET_BUG] Can't deploy a contract

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#299]
**Describe the bug**
First, the deploy button is hidden on smaller screens (or larger fonts)
Second, after pressing deploy in the sandbox a red box appears

**To Reproduce**
1. Go to 'https://testnet-explorer.blockstack.org.'
2. Click on 'Sandbox', then 'Deploy Contract'
3. Edit the template contract

**Expected behavior**
Either deploy the contract or provide information why it is not possible.

**Screenshots**
![Screenshot from 2021-01-11 14-55-02](https://user-images.githubusercontent.com/1449049/104190891-08999600-541d-11eb-8a03-edd794406b92.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser Firefox

**Additional context**
@timstackblock

**Comment by aulneau** [comment]
I need to update the REPL, which should fix this. Thanks for the issue, i'll let you know when it's fixed 👍

**Comment by aulneau** [comment]
This has been fixed!
