### ISSUE TITLE
unlocked STX are not reflected in the available balance ST97B09CCCHE31FTHR97ZKAF0VF3DD1XR6JCNJ29 

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#304]
**Describe the bug**
Unlocked STX are not reflected in the available balance ST97B09CCCHE31FTHR97ZKAF0VF3DD1XR6JCNJ29 

https://explorer-git-feat-coinbase-improvements.blockstack.vercel.app/address/ST97B09CCCHE31FTHR97ZKAF0VF3DD1XR6JCNJ29?chain=testnet

**To Reproduce**
1. Go to the link above
2. You will notice that the unlocked STX are greater than the balance
3. This looks like a bug but it may not be if the sent amount accounts for the difference
4. Once I get the mainnet address I can check, creating this issue as a placeholder

**Expected behavior**
Balance reflects unlocked tokens

**Screenshots**
<img width="1348" alt="Screen Shot 2021-01-13 at 9 56 02 AM" src="https://user-images.githubusercontent.com/49165468/104468538-91334600-5585-11eb-8052-6e0a5c40a5c4.png">

**Comment by aulneau** [comment]
This is not a bug -- this view does not account for any sent amounts due to it happening in stacks 1.0

**Comment by timstackblock** [comment]
Once the transaction data is there it will be obvious why the unlocked value is greater than the current STX balance, closing this issue.
