### ISSUE TITLE
Txs pending for a longer time disappear from the recent list

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#316]
**Describe the bug**
After an hour or so, I wasn't able to find the following transaction in the recent list: https://explorer.stacks.co/txid/0x2147731879acfc0aba0ed7546780ccbb19126785ec8de5d911cfb974673e0575?chain=mainnet

It is still pending at the time of writing. Opening the URL directly shows the transaction- is the API seems to still return the data.

**Comment by aulneau** [comment]
This will be fixed with #333. I had implemented a time based filter for the list due to an issue early in the testnet.

**Comment by choroni** [comment]
I have the same problem, the transaction is still pending for 24 hours
https://explorer.stacks.co/txid/0x8e4ac474364883f6fe5d4eadb720b4e5030bc1dd295ffb87fb7d79cdbbd9b169?chain=mainnet  Have you resolved?
