### ISSUE TITLE
False positive testnet address detection

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/explorer#317]
![image](https://user-images.githubusercontent.com/1618764/104731571-2e37df80-573c-11eb-880f-e09a81b16a8d.png)

**Comment by jeffdomke** [comment]
Is this in prod? I thought we discussed not showing these notifications this way? If so I guess I'll just open a new ticket with my suggestion.

**Comment by aulneau** [comment]
This false positive behavior has been resolved, closing issue. @jeffdomke if you have suggestions, please do open a new ticket.
