### ISSUE TITLE
Contract deploy view: Show call arguments

### ISSUE THREAD

**Issue by agraebe** [blockstack/explorer#324]
It would be great to show arguments for the contract call that is still pending. It seems the current API doesn't return the data, but we should check with @zone117x what possibilities we have to expose this

How to display: Just like for completed contract calls
Why: Helpful for testing purposes, gives you peace of mind

**Comment by markmhx** [comment]
@agraebe think this would be still helpful / relevant?

**Comment by agraebe** [comment]
yes

**Comment by aulneau** [comment]
I'm confused by this issue. Is the request to show the function arguments on pending contract call pages?

**Comment by agraebe** [comment]
ah, I just checked the most recent pages and this is already available. looks like it was implemented but the issue wasn't attached to the change. can close
