### ISSUE TITLE
Display network switch modal when on address of other chain

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#334]
It's possible that a user could navigate to or arrive at an address page for the address of a different mode, eg: viewing a testnet address while their app is returning mainnet data, and the reverse.

We are currently checking to see if the user arrives on the application intending to go to a different chain id via the `chain=[mode]` query parameter. If the query param is not included, most of the time we have no ability to infer which mode the user was expecting/hoping to see data from. However, adresses innately are of a certain mode, and as such we can check it and provide a similar experience as we do with the chain query param.

cc @jeffdomke -- i think this is the behavior you're hoping for (removing the inline messaging from the address page)

**Comment by Eshwari007** [comment]
Test passed with popup toast indicating which chain mainnet or testnet the user is in
