### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by choroni** [blockstack/explorer#338]
Please help
Transaction or hsh not found, I sent my STX tokens to kucoin and it was pending for 24 hours, now not even the hash is found
0x8e4ac474364883f6fe5d4eadb720b4e5030bc1dd295ffb87fb7d79cdbbd9b169

**Comment by dnxt001** [comment]
same like me

**Comment by markmhx** [comment]
@choroni @dnxt001 This appears to have been resolved by https://github.com/blockstack/stacks-blockchain/issues/2365. Please comment again if you're still facing problems here.
