### ISSUE TITLE
Patch issues with address page in relation to unlocking

### ISSUE THREAD

**Issue by markmhx** [blockstack/explorer#348]
We've gotten reports from some users who seem confused as to whether they've unlocked all of the STX that _should_ be unlocked by now. I've generally found it helpful to cross-check the graph we have on the legacy Explorer's address page to confirm whether the information shown on the new Explorer is correct.

Adding a link to the legacy address page with a note about how it can be used to cross-check the unlocking status might help clarify things for users who'd otherwise mis-calculate just how much they should have unlocked already:

> ℹ️ Expecting different amounts here? [View unlocking graph](#) on the legacy Stacks Explorer to examine unlocking events by date

<img width="359" alt="Screen Shot 2021-01-27 at 14 12 58" src="https://user-images.githubusercontent.com/28991/105995901-eb65f800-60a9-11eb-982b-6455bb1aa10d.png">

![image](https://user-images.githubusercontent.com/28991/105995659-96c27d00-60a9-11eb-99d2-3c1458214c9e.png)

cc @GinaAbrams @ryanarndtcm

**Comment by cuevasm** [comment]
This would be a good interim help solution for sure. RE: Comment in Discord, I think we'll have even more luck showing this link in the wallet.

**Comment by GinaAbrams** [comment]
Could we add a version of the unlocking graph into the new explorer?

**Comment by markmhx** [comment]
Yep, @GinaAbrams mind creating a separate issue for that request?

**Comment by GinaAbrams** [comment]
yep added a new one.

**Comment by muneeb-ali** [comment]
What's the URL of the legacy explorer?

**Comment by agraebe** [comment]
https://explorer.legacy.blockstack.org/

**Comment by andresgalante** [comment]
After discussing with the team, it was decided to take these actions:

- [ ] for unlocking addresses (or all if conditional not possible):
    - add link to read more / forum post with info about genesis data dump @muneeb-ali @GinaAbrams 
    - Change copy from `total balance` to `unlocked balance` @hstove @markmhx
- [ ] Remove available balance @hstove @markmhx 
- [ ] Hide current unlocked vs. locked component @hstove @markmhx 
- [ ] Open an issue for DevOps to redirect from the legacy to the new explorer @markmhx
