### ISSUE TITLE
Requesting tweaks to the network switcher modal

### ISSUE THREAD

**Issue by hstove** [blockstack/explorer#349]
The network switcher in the explorer is super helpful. I know we've given good thought to the modal for "are you sure you want to switch networks?", and we don't want to confuse our users. However, I have found that modal to be a bit of a pain, and it only gets in my way (personally).

Here is what I want:

- If I open a URL with `?chain`, always switch the network for me automatically

A compromise:

- Add a checkbox to the 'switch networks' modal to say "don't ask me again". Set a cookie and don't show me this ever again 😄

**Comment by Eshwari007** [comment]
Test passed with new network toast model
