### ISSUE TITLE
Chrome bug: clicking the transaction link for a pending transaction brings up Transaction not found message

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#357]
**Describe the bug**
When a user clicks on a pending transaction using chrome the Transaction not found message displays

Video of bug: http://somup.com/crnVrtospa

<img width="1433" alt="Screen Shot 2021-02-01 at 4 27 06 PM" src="https://user-images.githubusercontent.com/49165468/106520381-b3e0bc80-64aa-11eb-8bf9-c4df88b9a360.png">

**Comment by aulneau** [comment]
I can't recreate this. Closing unless someone else can recreate it. @timstackblock can you try again?
