### ISSUE TITLE
Add a "Total" field to match legacy Explorer behavior

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/explorer#358]
**Is your feature request related to a problem? Please describe.**

Legacy explorer has a field called "Total" which is computed by adding "Available + Locked" tokens. The current Explorer shows "Available" and "Locked" tokens separately, but doesn't display a "Total" in the same way. This is confusing for users, especially those who are used to the legacy explorer.

For example, compare
https://explorer.stacks.co/address/SPZPBP5J4V9B8R8XV312XNA8608JZ96EF28YT2WP?chain=mainnet

with
https://explorer.legacy.blockstack.org/address/stacks/SPZPBP5J4V9B8R8XV312XNA8608JZ96EF28YT2WP

**Describe the solution you'd like**

Mimic legacy Explorer behavior by adding a field that shows Available + Locked balance.

**Comment by markmhx** [comment]
I'm closing this out since it's currently getting addressed by https://github.com/blockstack/explorer/issues/362.
