### ISSUE TITLE
Support total, unlocked and locked balances on address page

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/explorer#362]
Suggestion from Muneeb: only show available balance and the currently locked number and display a percent with currently locked i.e., 10 STX currently locked (77% of unlocking completed)

**Comment by markmhx** [comment]
I believe we'll tackle this as part of the standardization effort re: balances tracked here: https://github.com/blockstack/ui/issues/74

cc @jasperjansz

**Comment by jasperjansz** [comment]
Design: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2599%3A21295

You can page through the states of stacking/locked STX using the toggles in the right panel: 
![image](https://user-images.githubusercontent.com/25477905/107637486-7e885b80-6c6e-11eb-8968-60eb7f3ce893.png)

All 4 states are in the Components page
