### ISSUE TITLE
Limited Events Display for Contract Call

### ISSUE THREAD

**Issue by tyGavinZJU** [blockstack/explorer#364]
**Describe the bug**
I used **send_many contract** @hstove  to transfer the tokens to 200 addresses.
https://explorer.stacks.co/txid/0x8bbf0907db143821d4bcfa22c3c6958a08f28e7f9a73b1db4ec48cd7f4f1a968?chain=mainnet

But the Event only show 95 of them, but I transferred 200 addresses. And I have checked it manually, it shows their balance is correct but no transaction related.
![WechatIMG1974](https://user-images.githubusercontent.com/37820916/106993839-8ea7c300-67b6-11eb-8b95-863bf32def3b.jpeg)
<img width="968" alt="截屏2021-02-05 下午1 32 37" src="https://user-images.githubusercontent.com/37820916/106993885-abdc9180-67b6-11eb-9f6d-67dd190ea281.png">

I have tried it several times and it seems the 95 is a limit.

Transaction ID 0x8bbf0907db143821d4bcfa22c3c6958a08f28e7f9a73b1db4ec48cd7f4f1a968

**Expected behavior**
Show all the events, that will be super useful to prove.

**Comment by tyGavinZJU** [comment]
Will update in
blockstack/stacks-blockchain-api#441

**Comment by zone117x** [comment]
@aulneau note that the events returned for a transaction are paginated, as the list can be thousands of items long. `event_offset` and `event_limit` can be used, see here for usage: https://blockstack.github.io/stacks-blockchain-api/#operation/get_transaction_by_id

**Comment by timstackblock** [comment]
@aulneau 
I don't see any difference in the staging build below

https://explorer-git-feat-misc-fixes-blockstack.vercel.app/txid/0x8bbf0907db143821d4bcfa22c3c6958a08f28e7f9a73b1db4ec48cd7f4f1a968?chain=mainnet

and the existing prod build

https://explorer.stacks.co/txid/0x8bbf0907db143821d4bcfa22c3c6958a08f28e7f9a73b1db4ec48cd7f4f1a968?chain=mainnet

I was expecting pagination to be added maybe I am looking for the wrong thing could you please elaborate on the change.

**Comment by aulneau** [comment]
@timstackblock sure thing!


on staging (see "Load more" button)
<img width="1006" alt="Screen Shot 2021-02-24 at 8 32 41 AM" src="https://user-images.githubusercontent.com/11803153/109015595-e67d6f80-767a-11eb-8b14-adc0c2ed4006.png">

on production: (no load more button)
<img width="1041" alt="Screen Shot 2021-02-24 at 8 32 49 AM" src="https://user-images.githubusercontent.com/11803153/109015596-e7160600-767a-11eb-8dfb-40905f7d1df4.png">

**Comment by timstackblock** [comment]
Thank you I see this fix it caps at 199

**Comment by aulneau** [comment]
> Thank you I see this fix it caps at 199

Yep, that is the amount of events for this transaction :)
