### ISSUE TITLE
Number of transfers incorrect

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#366]
**Describe the bug**
The number of transfers is incorrect. There is only 1 transfer and 1 successful deployment and 1 failed deployment.
The explorer shows 3 transfers and two deployments

![Screenshot from 2021-02-09 22-47-42](https://user-images.githubusercontent.com/1449049/107433018-0f551f00-6b29-11eb-95d3-0673b423d5e2.png)

Account:
https://explorer.stacks.co/address/SP497E7RX3233ATBS2AB9G4WTHB63X5PBSP5VGAQ?chain=mainnet

**Expected behavior**
1 transfer, 1 contract

**Comment by markmhx** [comment]
I'm closing this since it's quite old, but please reopen if it's still actively relevant / you see it as a general pattern.
