### ISSUE TITLE
Flickering on scroll

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/explorer#391]
Things are flickering/loading on scroll, it's pretty annoying. Here's an example:

https://user-images.githubusercontent.com/25477905/108987400-8646f780-7693-11eb-961d-b9308a4a08e4.mov

**Comment by aulneau** [comment]
Yeah that is pretty significant. I am removing the video, maybe that will help with this rendering performance. @jasperjansz can you test to see if it happens in safari + firefox? I know that it does in chrome, but I haven't seen it happen elsewhere. Could be something to do with some optimizations they are trying to do.
