### ISSUE TITLE
Confusing UX between sending and delegating

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#406]
**Describe the bug**
Several users have transferred funds to delegatee addresses instead of delegating.

For example: https://explorer.stacks.co/txid/0x14d7cbfab4aa06b5d983b86abebdfb43bfd7f609f743335a9fe6bb875cc1b703?chain=mainnet

**Expected behavior**
Users should be warned if they transfer stx to a well known pool address.

**Comment by aulneau** [comment]
Is this an explorer issue or a wallet issue?

**Comment by friedger** [comment]
@aulneau Ups, indeed
