### ISSUE TITLE
Fix display of unlocking schedule text in dark mode

### ISSUE THREAD

**Issue by markmhx** [blockstack/explorer#412]
Much of the text currently disappears compared to in light mode where it's visible:

![image](https://user-images.githubusercontent.com/28991/111864429-2295ae80-8961-11eb-93d2-7e91ef1c407e.png)

**Comment by CharlieC3** [comment]
This also happens in other areas while in dark mode too. Like when adding a network:
![Screen Shot 2021-04-20 at 2 53 39 PM](https://user-images.githubusercontent.com/2747302/115448947-465e4580-a1e8-11eb-9ceb-169cb91643c3.png)
