### ISSUE TITLE
Balance shown incorrectly

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#426]
**Describe the bug**
My balance does not take into account send many txs.

https://explorer.stacks.co/address/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60?chain=mainnet

![Screenshot from 2021-04-09 10-23-11](https://user-images.githubusercontent.com/1449049/114151648-9e11cc80-991d-11eb-93db-8dfb3e963c4a.png)

https://stacks-node-api.blockstack.org/v2/accounts/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60
![Screenshot from 2021-04-09 10-23-52](https://user-images.githubusercontent.com/1449049/114151726-b4b82380-991d-11eb-930a-5aaed184c827.png)

Actual balance: 5,642.661867 STX

**Comment by zone117x** [comment]
Looks to be correct on the API side: https://stacks-node-api.blockstack.org/extended/v1/address/SP1K1A1PMGW2ZJCNF46NWZWHG8TS1D23EGH1KNK60/stx
```json
{
"balance": "5642661867",
"total_sent": "140658807588",
"total_received": "129044691406",
"total_fees_sent": "8025731",
"total_miner_rewards_received": "17264803780",
"lock_tx_id": "",
"locked": "0",
"lock_height": 0,
"burnchain_lock_height": 0,
"burnchain_unlock_height": 0
}
```

**Comment by friedger** [comment]
By now, the explorer shows the correct value as well. What could be the cause of the difference? Node not in sync?
