### ISSUE TITLE
Failed to  request STX  on testnet.

### ISSUE THREAD

**Issue by louyaming** [blockstack/explorer#432]
![image](https://user-images.githubusercontent.com/34370955/115212581-40f2f380-a133-11eb-9074-e7d0a1c78263.png)

**Comment by markmhx** [comment]
This appears to be working now. @louyaming please reopen if you still see this error!

**Comment by louyaming** [comment]
> This appears to be working now. @louyaming please reopen if you still see this error!
Thank you for your reply. I have tried again and it can work normally.👍
