### ISSUE TITLE
Add regtest to default network list

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/explorer#436]
**Is your feature request related to a problem? Please describe.**
The `regtest` network is not currently listed in the Explorer's interface by default:
![Screen Shot 2021-04-27 at 10 42 04 AM](https://user-images.githubusercontent.com/2747302/116261005-38a74380-a745-11eb-9147-08c20d80d335.png)

This makes it more difficult for users to use the regtest network than the mainnet or testnet networks.

**Describe the solution you'd like**
Add the `regtest` network to the default network list, under the `testnet` network if possible. A new ENV var should be created to support this, called `NEXT_PUBLIC_REGTEST_API_SERVER`.

**Comment by agraebe** [comment]
@aulneau I'll take this one - it'll be helpful for the nft onboarding tutorial. it'll use the regtest
