### ISSUE TITLE
recuperacion de token 

### ISSUE THREAD

**Issue by razpurge** [blockstack/explorer#446]
There is a possibility of recovering this transfer that you do without the memo for not knowing how to transfer

99,00 STX
SP34FXH035DMS7BDZCHF17Q0P0QXPT713BZZGBER4
SP1P72Z3704VMT3DMHPP2CB8TGQWGDBHD3RPR9GZS
0xf6a911512fd3c55afd8e85a91864db0d75fb529d582369d469b4f7dbe4dc96bf
0.00018 STX
#15805
Hace 19 horas
0xa847f231c4261882fa4f737b6d14f2c3bb3ef17de3a70a52b0033b929499cce3

**Comment by 314159265359879** [comment]
This is a transaction to Binance, without a memo. That means they can not automatically credit it to your account but you can contact them with these details and I am sure they can sort it out for you. Nobody here can do anything about it though. 

This issue can be closed.
