### ISSUE TITLE
[Microblocks] Update txid page

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/explorer#455]
**Individual transactions**
- Update to the title to show the state (pending, in microblock, or in anchor block): https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A1198
- Add component to show historical state changes: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A878 (this will be used in the transactions details view on the web wallet too)
- If included in anchor block, show number of anchor block confirmations since: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A878

**Comment by Eshwari007** [comment]
Test passed for the first two use case.
Note:
If included in anchor block, show number of anchor block confirmations since: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=2847%3A878 will not be implemented as it may be confusing for user
