### ISSUE TITLE
Stx balance does not take into account stacked stx

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/explorer#458]
**Describe the bug**
This is shown:
![image](https://user-images.githubusercontent.com/33360391/121491577-5fa89480-c9d6-11eb-897d-b420b1078499.png)

But this differs from the available balance as seen in the explorer
![image](https://user-images.githubusercontent.com/33360391/121491691-7bac3600-c9d6-11eb-9472-ef6ac9e70632.png)

Transaction ID 
n/a

**To Reproduce**
1. Go to explorer
2. Click on sandbox
3. Login with stacked account
4. See error 97,9... stx balance

**Expected behavior**
I expect to see the available balance less than 1 stx.

**Screenshots**
See above.

**Desktop (please complete the following information):**
Windows 10, Chrome/Firefox

**Additional context**
Perhaps this can be resolved together with this issue for the Web wallet 
https://github.com/blockstack/stacks-wallet-web/issues/1273

**Comment by markmhx** [comment]
I'm closing since it appears the account balance and total balance across the two screenshots shows the same value (97.999145 STX)?
