### ISSUE TITLE
bug: address page data does not update

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#466]
if navigating to an address page via the search, and then navigating to other address pages from that page, when a user hits the back button, the data does not update correctly to reflect the correct address. this should be resolved by https://github.com/blockstack/explorer/issues/465

**Comment by aulneau** [comment]
this can be tested in https://github.com/blockstack/explorer/pull/469

**Comment by Eshwari007** [comment]
Test passed hence moving it to QA Done
