### ISSUE TITLE
Transaction 'Pending' for Two Weeks — Still Churning on App, URL is Not Valid 

### ISSUE THREAD

**Issue by alanthonyc** [blockstack/explorer#473]
I've long since given up on this transaction, but my wallet app still shows it as "Pending".

The URL returns a 404.

https://explorer.stacks.co/txid/0xf9bd590f045730166fac318f9b7041403b7471dd32897efb96c9a93c4cf2fbb1?utm_source=stacks-wallet&chain=mainnet

**Comment by markmhx** [comment]
I'm closing but please reopen with a comment if you're still having issues with transactions.
