### ISSUE TITLE
Text in unlocking schedule doesn't appear in dark mode

### ISSUE THREAD

**Issue by tirumerla** [blockstack/explorer#480]
**Describe the bug**
Viewing vesting schedule in dark mode, the text in the columns defaults to the same color as the background.

**To Reproduce**
1. Go to https://explorer.stacks.co/address/<public_address>
2. Switch to dark mode
3. Click on "View Schedule" under STX Balance.

**Expected behavior**
I should be able to see the vesting schedule similar to what i see in light mode.

**Screenshots**
<img width="941" alt="Screen Shot 2021-07-10 at 10 10 19 PM" src="https://user-images.githubusercontent.com/57160285/125183504-cedaf980-e1cb-11eb-98ee-b2f99c95f2b4.png">

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser - Brave
 - Version - 1.24.84 Chromium: 90.0.4430.93

Similar issue as #460

**Comment by fbwoolf** [comment]
> @fbwoolf did you fixed this issue in the recent update of the dark mode in the explorer?

@andresgalante no I didn't know this was an issue. I never addressed the unlocking schedule dark mode. Most of my dark mode changes involved microblocks.

**Comment by markmhx** [comment]
I believe this was resolved with https://github.com/blockstack/explorer/pull/521
