### ISSUE TITLE
Odd behaviour with selected network

### ISSUE THREAD

**Issue by kyranjamie** [blockstack/explorer#481]
I had microblocks set as the network, currently offline. Looking at this tx, on mainnet, the network switching functionality isn't working.

It opens the tx, then it flashes away. 

https://user-images.githubusercontent.com/1618764/125458679-ed17f23f-2c47-4772-a68d-e36b9e804a96.mp4

**Comment by fbwoolf** [comment]
Do you mean `mainnet` in the description, not `mircoblocks`?

**Comment by kyranjamie** [comment]
> Do you mean mainnet in the description, not microblocks?

No, I didn't. I'd added a microblock instance to the dropdown, and noticed this behaviour then. Perhaps because the microblock API was, at the time, offline.

**Comment by Eshwari007** [comment]
@kyranjamie Any info on how to add Microblocks as an instance in the network will be a great help to test the issue out

**Comment by kyranjamie** [comment]
@Eshwari007 Sorry for the confusion. This issue is _nothing to do with microblocks_, I just happened to notice the issue when working on microblocks.

When you have _any_ network selected from the dropdown list, you'll likely experience the same issue.

**Comment by Eshwari007** [comment]
Test passed.
Closing the ticket
