### ISSUE TITLE
[Sandbox - Faucet] Button to enable PoX for 12 cycles in testnet

### ISSUE THREAD

**Issue by friedger** [blockstack/explorer#483]
**Is your feature request related to a problem? Please describe.**
I would like to test stacking on testnet

**Describe the solution you'd like**
If proof of burn is active there should be a button on the faucet page that triggers a transaction signed by a faucet address. The transaction stacks sufficient stacks for 12 cycles such that PoX is active for the next cycle after the tx was confirmed.

**Describe alternatives you've considered**
Run devnet/local testnet.

**Additional context**
See discussion here: https://discord.com/channels/621759717756370964/691807526118883418/864929318919733262

**Comment by philipdesmedt** [comment]
I have a similar issue. Been trying to stack on a local private testnet (through ./manage.sh private-testnet up from stacks-local-dev repo).

I stack 55M. Total liquid supply on my private testnet is 1.5B (which means I am stacking >1%). 

This is what /v2/pox returns:
{"contract_id":"ST000000000000000000002AMW42H.pox","pox_activation_threshold_ustx":15082676063198,"first_burnchain_block_height":0,"prepare_phase_block_length":1,"reward_phase_block_length":4,"reward_slots":8,"rejection_fraction":3333333333333333,"total_liquid_supply_ustx":1508267606319817,"current_cycle":{"id":490,"min_threshold_ustx":47140000000000,"stacked_ustx":55479999000000,"is_pox_active":false},"next_cycle":{"id":491,"min_threshold_ustx":47140000000000,"min_increment_ustx":3142224179832,"stacked_ustx":55479999000000,"prepare_phase_start_block_height":2454,"blocks_until_prepare_phase":3,"reward_phase_start_block_height":2455,"blocks_until_reward_phase":4,"ustx_until_pox_rejection":14186730892300068534},"min_amount_ustx":47140000000000,"prepare_cycle_length":1,"reward_cycle_id":490,"reward_cycle_length":5,"rejection_votes_left_required":14186730892300068534,"next_reward_cycle_in":4}

**Comment by aulneau** [comment]
> If proof of burn is active there should be a button on the faucet page that triggers a transaction signed by a faucet address. The transaction stacks sufficient stacks for 12 cycles such that PoX is active for the next cycle after the tx was confirmed.

This is more a request for `stacks-blockchain-api` I think, as the keys are all contained in that. The explorer could have a button, but it would simply call that function from the api.

**Comment by friedger** [comment]
For participation below 25%, there is a fixed price per reward slot.

The price per block on regtest is 25% / 8 = 3.125% that is 128M STX per slot.

On testnet, one slot price for participation below 25% is 5,13M STX. However, the 1% threshold to activate pox is 41,010.02m STX.

**Comment by diwakergupta** [comment]
Quick follow up here that PoX should get activated on testnet with the next cycle (63). Hiro is also working on a more durable solution internally to ensure PoX remains active on testnet. I'm going to close out this issue for now, thanks!
