### ISSUE TITLE
Nonce is 0 in Explorer for STX transaction

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#487]
Environment:Testnet

User was able to send STX between two accounts in web wallet
User then selects the activity of the transaction and navigates to explorer
User notices that the nonce was =0 which should is inaccurate
<img width="864" alt="Screen Shot 2021-07-20 at 12 27 52 PM" src="https://user-images.githubusercontent.com/38872890/126372749-8c973f37-a25c-44cc-a089-f6a32a8a9b7e.png">
 cc @markmhx @beguene @fbwoolf

**Comment by markmhx** [comment]
@beguene does this appear to be the same issue as the one you resolved here in the desktop wallet? https://github.com/blockstack/stacks-wallet/issues/874

**Comment by beguene** [comment]
@markmhx @Eshwari007 wrote that it's with the web wallet.
Anyway a nonce of 0 is not an issue as such, the first transaction will always be having a nonce = 0
see here https://explorer.stacks.co/txid/0x4567f0e20df0f2627f7c6fdbb03052d278c9ad3b4e4de3263e672c3091bdf3de?chain=testnet
I don't think this is an issue.
