### ISSUE TITLE
[PR 469]Switching network issues when not on homescreen

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#489]
PR:https://github.com/blockstack/explorer/issues/489
URL:https://explorer-git-feat-cleanup-data-blockstack.vercel.app/transactions?chain=mainnet

User switches the network via the dropdown in explorer,the url seems to be updated however the drop down isnt and a popup keeps coming up in preventing user to navigate further until user selects 'stay on ' option
User also notices that the network isnt switching well when its tweaked via url esp for regtest.

Attaching the video for perusal

https://user-images.githubusercontent.com/38872890/126565452-031447d6-a4b0-446b-aea5-eaf8efb3c64a.mov

**Comment by Eshwari007** [comment]
Switching from testnet to mainnet
<img width="1307" alt="Screen Shot 2021-07-21 at 6 26 14 PM" src="https://user-images.githubusercontent.com/38872890/126567908-f9846914-f3a9-4873-92ae-8639ac87dbe9.png">

**Comment by markmhx** [comment]
@Eshwari007 Can you include a mention of the PR you're testing when filing these bugs?

**Comment by Eshwari007** [comment]
@markmhx I did included the PR link, but github converted it to 469 as its the PR #

Pr info:https://github.com/blockstack/explorer/pull/469.

**Comment by Eshwari007** [comment]
Also notice when I change the network via url,it works for mainnet and test net only,reg test isnt working when I tweak the network via url.

**Comment by aulneau** [comment]
ah yes thank you, the issue presents itself when you are not on the home screen -- need to bring over some code to each page.

**Comment by aulneau** [comment]
fixed with https://github.com/blockstack/explorer/pull/469/commits/86e43e607774aa665e0a0ec647c79c2bbd42922a (still building)

**Comment by Eshwari007** [comment]
Also notice that when user switching from testnet to mainnet or regtest to mainnet,The popup yet indicate ,do you want to change to testnet(which is inaccurate).This was tested on main explorer page as well.

Attaching video for perusal

https://user-images.githubusercontent.com/38872890/126654658-39fb85ba-a9d1-48e7-8ee9-0cdb4a5d9bfe.mov

**Comment by aulneau** [comment]
@Eshwari007 no need to test for `regtest`. I'm going to remove that feature as we are going to be shutting down regtest anyways
