### ISSUE TITLE
Update transaction pages to use query

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#49]
Right now, all the types of tx pages are manually created. We should have one tx page that gets some data, eg the tx, and determines the type of that transaction and displays the accurate sections. Types here: https://www.npmjs.com/package/@blockstack/stacks-blockchain-sidecar-types

**Comment by kyranjamie** [comment]
These have been updated, see [`@blockstack/stacks-blockchain-sidecar-types`](https://www.npmjs.com/package/@blockstack/stacks-blockchain-sidecar-types)
