### ISSUE TITLE
[PR 469]Sandbox page is missing

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#490]
Testing the issue in :https://explorer-git-feat-cleanup-data-blockstack.vercel.app/sandbox/deploy
This is related to the PR:https://github.com/blockstack/explorer/pull/469

Page missing when user selects the Sandbox tab
The page is not to be found
<img width="1395" alt="Screen Shot 2021-07-21 at 5 58 32 PM" src="https://user-images.githubusercontent.com/38872890/126565690-da1aa97a-ddd7-4302-a165-f2cd8fbf1f05.png">

**Comment by markmhx** [comment]
@Eshwari007 Can you provide some additional context as to what you were testing when this arose?

**Comment by aulneau** [comment]
yep, this is still WIP, thanks for the issue tho
