### ISSUE TITLE
Filter selections causes network mismatch 

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#497]
Environment:Testnet
PR:#493
URL:https://explorer-git-feat-microblocks-final-blockstack.vercel.app/transactions?chain=testnet

User selects the filter on Transaction tab
User unselect all of the selection
User notices that the page is asking to switch network 
User notices that the behavior isnt user friendly
Is there a flow that we can work here? Making it as a bug but can be changed to enhancement if needed.

https://user-images.githubusercontent.com/38872890/127397945-853a6d25-af90-4b17-a38e-8bf74e62bdc3.mov

**Comment by markmhx** [comment]
@aulneau has a local fix for this

**Comment by Eshwari007** [comment]
Tested the issue both on testnet and mainnet.
Test passed

**Comment by fbwoolf** [comment]
@aulneau can we close this issue?

**Comment by aulneau** [comment]
Yep, it's resolved in the microblocks deployment
