### ISSUE TITLE
Request STX in Sandbox-Explorer is throwing error

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#499]
URL:https://explorer-git-feat-microblocks-final-blockstack.vercel.app/sandbox/faucet

User tries to add more STX via the faucet,this has worked in the past abut seems to be broken now
<img width="1313" alt="Screen Shot 2021-07-28 at 5 56 26 PM" src="https://user-images.githubusercontent.com/38872890/127401440-3461964a-0c20-4937-961d-7282b6089e49.png">

**Comment by aulneau** [comment]
This is unrelated to the explorer. @CharlieC3 i was under the impression this would no longer be an issue with the reset?

**Comment by CharlieC3** [comment]
> This is unrelated to the explorer. @CharlieC3 i was under the impression this would no longer be an issue with the reset?

@lgalabru ?

**Comment by lgalabru** [comment]
Is the API using the right keypair?

**Comment by CharlieC3** [comment]
@lgalabru You're right, I don't think it was. @Eshwari007 Can you try again now?
