### ISSUE TITLE
Microblocks: Icon/status incorrect on contract-call pages

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/explorer#509]
**Describe the bug**
Bug found in microblocks PR needs to be looked at prior to release, the icon is missing and the status is incorrect on the contract-call pages. See image:

![image](https://user-images.githubusercontent.com/6493321/128722490-d50a5f7b-6112-4c69-8b3c-f1a2bc2e3e7c.png)

**Comment by fbwoolf** [comment]
![image](https://user-images.githubusercontent.com/6493321/128751375-9dc9cf5d-b94d-4761-9ad5-22b796eff5f9.png)

@aulneau I pushed up a commit to the microblocks branch that should fix this.

**Comment by Eshwari007** [comment]
Test passed in both testnet and mainnet

**Comment by fbwoolf** [comment]
@aulneau once you check the commit on this again I think this can be closed.

**Comment by aulneau** [comment]
yep! great work
