### ISSUE TITLE
TransactionDetails transforms

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#51]
Depending on the type of transaction, the top section displays different labels for the same key:

![Screen Shot 2020-04-07 at 8 45 15 AM](https://user-images.githubusercontent.com/11803153/78676529-2d6c4600-78ac-11ea-8826-303a859c01a0.png)
![Screen Shot 2020-04-07 at 8 45 21 AM](https://user-images.githubusercontent.com/11803153/78676530-2e04dc80-78ac-11ea-86a5-296d3265f56b.png)
![Screen Shot 2020-04-07 at 8 45 27 AM](https://user-images.githubusercontent.com/11803153/78676532-2e04dc80-78ac-11ea-8cfa-7be77bda6bc0.png)
![Screen Shot 2020-04-07 at 8 45 32 AM](https://user-images.githubusercontent.com/11803153/78676534-2e9d7300-78ac-11ea-8b3b-91a84d72818a.png)
![Screen Shot 2020-04-07 at 8 45 37 AM](https://user-images.githubusercontent.com/11803153/78676535-2e9d7300-78ac-11ea-8bb2-859064c0d229.png)

Right now it's only set up to display one variation of the data, we need to model out an example of each TX and have the page display it correctly.

**Comment by kyranjamie** [comment]
I briefly discussed this with Jasper a while ago, prompting the idea that each tag corresponds 1:1 with the `tx_type`s

**Comment by aulneau** [comment]
@kyranjamie I would love that

**Comment by kyranjamie** [comment]
Closing this, let's use one icon per tx type.
