### ISSUE TITLE
Function arguments should show up on microblocks deployment

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#510]
Previously the function argument section would contain the functions passed to the method -- but they are no longer present. Could just be an incorrect boolean

before: 
![Screen Shot 2021-08-10 at 8 54 37 AM](https://user-images.githubusercontent.com/11803153/128879702-0d62d67c-8298-4cb5-8977-887ee90da643.png)

in the microblocks branch:
![Screen Shot 2021-08-10 at 8 54 42 AM](https://user-images.githubusercontent.com/11803153/128879716-d0d3fc23-cdd9-4858-a865-45a1bcdc8cf3.png)

**Comment by fbwoolf** [comment]
I'll start this one.

**Comment by fbwoolf** [comment]
I believe this is fixed with my most recent commit.

**Comment by aulneau** [comment]
> I believe this is fixed with my most recent commit.

it is not, see https://explorer-git-feat-microblocks-final-blockstack.vercel.app/txid/0x00dfca7e379ffe1972017af770e3409a3a67114754a372cc864a27dc7d86afea

**Comment by fbwoolf** [comment]
Pushed up a new commit to fix this.

**Comment by aulneau** [comment]
awesome, confirmed it fixes it, thank you! closing this
