### ISSUE TITLE
Fix broken transaction page upon transition to anchor block

### ISSUE THREAD

**Issue by whoabuddy** [blockstack/explorer#518]
**Describe the bug**

I've noticed this a few times since the microblocks release, and now I think I'm starting to see a pattern:

If I have a pending transaction open in a tab, leave that tab for a while, and come back to check on it, I'm presented with a "Page not found" error and an empty switch network modal.

![image](https://user-images.githubusercontent.com/9038904/130323983-26f0e503-c387-4cd8-9c4a-4ea3437b38c4.png)

It appears related to when the transaction is included in an anchor block and the state tries to update:

- pending to confirmed in microblock, works as expected
- pending to failed, works as expected
- pending to confirmed in anchor block, shows image above

Refreshing the page shows the correct transaction state.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave

**Comment by whoabuddy** [comment]
Here is the related info from the console tab:

![image](https://user-images.githubusercontent.com/9038904/130334452-26629137-bdf6-4ec3-9529-fb0a75085afb.png)

Also in text below:

```
framework-5d05deef16fd4c089944.js:1 Error: Ct suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    at Si (framework-5d05deef16fd4c089944.js:1)
    at xi (framework-5d05deef16fd4c089944.js:1)
    at vi (framework-5d05deef16fd4c089944.js:1)
    at framework-5d05deef16fd4c089944.js:1
    at t.unstable_runWithPriority (framework-5d05deef16fd4c089944.js:1)
    at Wl (framework-5d05deef16fd4c089944.js:1)
    at Ql (framework-5d05deef16fd4c089944.js:1)
    at Hl (framework-5d05deef16fd4c089944.js:1)
    at fi (framework-5d05deef16fd4c089944.js:1)
    at No (framework-5d05deef16fd4c089944.js:1)
uu @ framework-5d05deef16fd4c089944.js:1
```

```
main-c6384a826dbb19afa6a3.js:1 Error: Ct suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    at Si (framework-5d05deef16fd4c089944.js:1)
    at xi (framework-5d05deef16fd4c089944.js:1)
    at vi (framework-5d05deef16fd4c089944.js:1)
    at framework-5d05deef16fd4c089944.js:1
    at t.unstable_runWithPriority (framework-5d05deef16fd4c089944.js:1)
    at Wl (framework-5d05deef16fd4c089944.js:1)
    at Ql (framework-5d05deef16fd4c089944.js:1)
    at Hl (framework-5d05deef16fd4c089944.js:1)
    at fi (framework-5d05deef16fd4c089944.js:1)
    at No (framework-5d05deef16fd4c089944.js:1)
le @ main-c6384a826dbb19afa6a3.js:1
```

```
main-c6384a826dbb19afa6a3.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
le @ main-c6384a826dbb19afa6a3.js:1
```

```
_app-19bf99ec13f50047b563.js:1 Duplicate atom key "sandbox.contract-call.view". This is a FATAL ERROR in
      production. But it is safe to ignore this warning if it occurred because of
      hot module replacement.
```

**Comment by diwakergupta** [comment]
I've seen this as well:

<img width="485" alt="Screen Shot 2021-08-20 at 9 18 01 AM" src="https://user-images.githubusercontent.com/15990/130458128-9cc8f4db-6015-4630-9439-448ae19bff43.png">

**Comment by markmhx** [comment]
Note that while this appears to have happened upon release of microblocks support, I've encountered this for transactions transitioning from pending directly to confirmed in anchor block. So any transition to anchor block appears affected atm.

**Comment by fbwoolf** [comment]
> Note that while this appears to have happened upon release of microblocks support, I've encountered this for transactions transitioning from pending directly to confirmed in anchor block. So any transition to anchor block appears affected atm.

All of @aulneau state changes with jotai were release with microblocks, so it is likely related to those changes not microblocks.

**Comment by aulneau** [comment]
Ah -- this makes sense. There is certain data that isn't available when a transaction is pending (contract interface, etc), and as such, when the transition between pending -> confirmed happens, the new data is available, and as such will be fetched. But we need to wrap that data in a Suspense wrapper, else the error @whoabuddy shows will happen. 

The network confirm dialog is an interesting bug -- I know we wanted to move away from this convention entirely and simply switch behind the scenes -- @markmhx is that the case? if so, we should do that and this kind of issue would go away as a result.

**Comment by aulneau** [comment]
I'd wrap the `[txid].tsx` in `<SafeSuspense fallback={<></>}>` for now. Do you have clear steps to repro the issue?

**Comment by fbwoolf** [comment]
I ended up doing this and seemed to fix it...

```
<SafeSuspense fallback={<LoadingPanel text="Loading transactions..." />}>
   <TabbedTransactionList limit={DEFAULT_LIST_LIMIT_SMALL} />
</SafeSuspense>
```

**Comment by fbwoolf** [comment]
I am running into it on the transactions list when filtering.

**Comment by aulneau** [comment]
Yeah -- looking at this more, there is logic currently to essentially put the last known set of filters as the placeholder while the new data fetches. [You can see that here.](https://github.com/blockstack/explorer/blob/main/src/components/tabbed-transaction-list.tsx#L75) The issue seems to happen when we filter too quickly:
- change filters
- query starts to load (previous query is set as placeholder)
- change filters again
- previous query is set to the one that has not completed yet
- throws suspense that is not caught

A quick fix would be to disable the button until the data has resolved, or debounce the filter buttons.

**Comment by fbwoolf** [comment]
Should we even be using Suspense for data fetching in production? https://reactjs.org/docs/concurrent-mode-suspense.html#using-suspense-in-practice ...it doesn't seem like it is supported yet?

**Comment by aulneau** [comment]
if you're interested, there are many wonderful discussions happening here https://github.com/reactwg/react-18/discussions, showing that suspense in the coming months will be fully supported, with almost no API change from what we're currently doing (and if any, it's all on libraries).

**Comment by markmhx** [comment]
Confirming re: @aulneau's [question above](https://github.com/blockstack/explorer/issues/518#issuecomment-903808944): yes let's remove the modal entirely.

Note that we should go back and QA related behavior or close the following issues upon removal:

https://github.com/blockstack/explorer/issues/360
https://github.com/blockstack/explorer/issues/334
https://github.com/blockstack/explorer/issues/349
https://github.com/blockstack/explorer/issues/481
https://github.com/blockstack/explorer/issues/514

**Comment by Eshwari007** [comment]
The explorer page was 'pending' and working fine till the moment user speed up the tx with a. new fee and it broke the page

**Comment by fbwoolf** [comment]
@Eshwari007 are you still testing this one? Hoping to merge the linked PR soon if can? Not sure will address all aspects of this issue but will address removing the switch network modal popping up.

**Comment by Eshwari007** [comment]
@fbwoolf Yes,I should wrap it up soon.Testing all the PR as mentioned above one by one

**Comment by Eshwari007** [comment]
Will retest the issue upon latest Chrome release as well.
