### ISSUE TITLE
Fix display of Stacking cycle information per address

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#520]
The most current release does not include the stacking cycle info card, it must have been disabled when the api improvements were added. We should see why it's not visible, and add it back in.

**Comment by fbwoolf** [comment]
> The most current release does not include the stacking cycle info card, it must have been disabled when the api improvements were added. We should see why it's not visible, and add it back in.

@aulneau can you provide any more info on this? I'm just not familiar with where it used to show up so I'm not sure what I'm looking for? Do you have an old image or can point me to where it shows up in the designs?

**Comment by aulneau** [comment]
Sure @fbwoolf it seems to be this https://github.com/blockstack/explorer/blob/f42bd01b9a28fd3a8b9e91c9de1b557a0af1ee92/src/components/balances/stx-balance-card.tsx#L174 seems like `isStacking` is not working for some reason

**Comment by fbwoolf** [comment]
> 
> seems like `isStacking` is not working for some reason

Took me a sec to get some locked STX setup in my test account, but this is showing up for me. Are you sure you had locked STX in your test account?

![Screen Shot 2021-09-09 at 4 02 01 PM](https://user-images.githubusercontent.com/6493321/132762336-20c074f1-ca1c-433e-8d7d-267747a536c2.png)

**Comment by aulneau** [comment]
I think the issue is more that https://github.com/blockstack/explorer/blob/f42bd01b9a28fd3a8b9e91c9de1b557a0af1ee92/src/components/balances/stx-balance-card.tsx#L181 is not showing up

**Comment by fbwoolf** [comment]
> I think the issue is more that
> 
> https://github.com/blockstack/explorer/blob/f42bd01b9a28fd3a8b9e91c9de1b557a0af1ee92/src/components/balances/stx-balance-card.tsx#L181
> 
> is not showing up

O, gotcha, now I see that component's code is all commented out. Ha, will fix!
