### ISSUE TITLE
Opening sandbox menu causes UI bug

### ISSUE THREAD

**Issue by fbwoolf** [blockstack/explorer#529]
![Screen Shot 2021-09-08 at 2 10 28 PM](https://user-images.githubusercontent.com/6493321/132571166-957c82ed-077e-4df8-9453-1c1fb789c924.png)

![Screen Shot 2021-09-08 at 2 52 08 PM](https://user-images.githubusercontent.com/6493321/132576190-cdbb1007-8bcb-4b0b-8782-21611b743145.png)

**Comment by kyranjamie** [comment]
Could this be related to React Query dev tools?

**Comment by aulneau** [comment]
No this was originally introduced in this PR https://github.com/blockstack/explorer/pull/435
