### ISSUE TITLE
Search bar for tx id is not returning results

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#530]
Mainnet
User attempts to input tx id 0xf0a0d2a25d87dd27f3563f8a39f6d0f072f618742edaa0394376b4aed531c1be and tried to serach in the explorer however no results were returned.But when user tweaked the url to include the tx id:https://explorer.stacks.co/txid/0x25c8d18513f9c32d303f035d792cbb3028b0779967d00e39f3a72660befdc557

The page returns accurate results that its yet 'Pending'
Seems like explorer has been broken as its not able to return results for search based by tx id.

cc @fbwoolf @GinaAbrams

**Comment by fbwoolf** [comment]
@GinaAbrams I have a fix for this so will put up a PR.
