### ISSUE TITLE
Fix "Add a network" option in menu

### ISSUE THREAD

**Issue by markmhx** [blockstack/explorer#532]
When I select "Add a network", the menu simply disappears and I don't see any error message in the console:

![image](https://user-images.githubusercontent.com/28991/132838838-e33657fb-e2e2-45fa-a94c-a6d13600b1a3.png)

**Comment by Eshwari007** [comment]
@markmhx Am in V2.16 Chrome and is able to view the  add network popup,may I know which version and browser did you find the issue with?Thx
<img width="410" alt="Screen Shot 2021-09-15 at 9 57 05 AM" src="https://user-images.githubusercontent.com/38872890/133447094-7362f0e0-8105-4f1f-adad-86254930ea06.png">

**Comment by Eshwari007** [comment]
Test passed and the network modal is looking good esp the ability to delete the new network modal which was custom 

https://user-images.githubusercontent.com/38872890/134065487-07f679a2-1990-4d58-a1e0-75185be9469d.mov

added

Quick finding:

1) When user adds new network and view the network menu,the new network is not added until you have a network toast popup on the explorer.
2) Can we hard code https:// for the url section as if the user tends to copy paste the url,they are thrown with error of the missing https ://

**Comment by fbwoolf** [comment]
> 
> 1. When user adds new network and view the network menu,the new network is not added until you have a network toast popup on the explorer.
> 

I think this looks ok ...maybe you were just removing/adding networks real quickly. I don't think this will be an issue for most users. 

> 
> 2. Can we hard code https:// for the url section as if the user tends to copy paste the url,they are thrown with error of the missing https ://
> 

This could definitely be an enhancement if you want to create another issue for it? I don't think I will add it to this work bc there are already a lot of code changes and I'd like to get it live asap.

Thanks for the feedback!
