### ISSUE TITLE
送金したSTXが着金しないので確認した

### ISSUE THREAD

**Issue by luna2319** [blockstack/explorer#537]
午前９時頃にOKcoinから出金した（完了と連絡が来た）STXが着金しないので、確認したくてトランザクションを確認していました。

**Comment by kyranjamie** [comment]
> [JP–EN] I was checking the transaction because I didn't receive the STX that I withdrew from OKcoin around 9am (I was informed that it was completed)

Do you have a transaction ID? If not, it's likely that Okcoin simply haven't sent your money yet. You'll need to talk to their support for this.
