### ISSUE TITLE
Can not load regtest explorer from explorer.stacks.co 

### ISSUE THREAD

**Issue by 314159265359879** [blockstack/explorer#539]
**Describe the bug**
Regtest not loading on explorer.stacks.co
![image](https://user-images.githubusercontent.com/33360391/133146254-e6838a97-0a86-41ca-bf11-f560c48cac65.png)
When I click on the red circle, I get the subsequent message lower middle of the page: You're viewing the mainnet explorer. It is not switching.
![image](https://user-images.githubusercontent.com/33360391/133146380-e3656484-7e6c-4676-b50f-53f9065f990b.png)

**To Reproduce**
1. Go to explorer.stacks.co
2. Click on Network (upper right corner)
3. Click on see screenshot: regtest
4. See error: You're viewing the mainnet explorer

**Expected behavior**
The regtest explorer should be shown, and I would like the ability to use the faucet.

**Screenshots**
See intro

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 

**Smartphone (please complete the following information):**
 - Version 92.0

**Additional context**
![image](https://user-images.githubusercontent.com/33360391/133146775-3a52f920-06f1-479b-98e1-765a4e048428.png)

**Comment by 314159265359879** [comment]
I think this is not yet solved the message has now changed to "...undefined explorer" and I am send to this URL when I am on the sandbox. When I am on the explorer's frontpage it appears to remain on mainnet when I click "regtest" in the network menu.

![image](https://user-images.githubusercontent.com/33360391/133784707-42deb419-5285-4e08-b0a9-6e2d147ceac5.png)

**Comment by fbwoolf** [comment]
> I think this is not yet solved the message has now changed to "...undefined explorer" and I am send to this URL when I am on the sandbox. When I am on the explorer's frontpage it appears to remain on mainnet when I click "regtest" in the network menu.
> 
> ![image](https://user-images.githubusercontent.com/33360391/133784707-42deb419-5285-4e08-b0a9-6e2d147ceac5.png)

This has been merged, but not released into production yet. Let me release it this morning for you!
