### ISSUE TITLE
Selection of new network in explorer points to mainnet

### ISSUE THREAD

**Issue by Eshwari007** [blockstack/explorer#545]
User added a new network via Web wallet as it wasnt able to do so via the explorer:https://github.com/blockstack/explorer/issues/532?
Upon navigating to explorer,user however can view the new network but when user selects the new network,it points to mainnet
<img width="400" alt="Screen Shot 2021-09-15 at 10 30 24 AM" src="https://user-images.githubusercontent.com/38872890/133452885-d85f6f15-7383-4107-ae00-ac3d8d63afe3.png">

**Comment by fbwoolf** [comment]
> User added a new network via Web wallet as it wasnt able to do so via the explorer:#532?
> Upon navigating to explorer,user however can view the new network but when user selects the new network,it points to mainnet

@Eshwari007 I don't see a new network in the list you attached as the image? Were you selecting `regtest`? I'll try to repro this but we do have a PR open for removing regtest from the network list and it was a known issue that selecting it wasn't working.

**Comment by Eshwari007** [comment]
<img width="415" alt="Screen Shot 2021-09-15 at 5 21 57 PM" src="https://user-images.githubusercontent.com/38872890/133511320-4483f978-480a-4561-9f9e-8593e57dc0df.png">
@fbwoolf  Attaching the network I selected which was directed to mainnet upon selection

**Comment by fbwoolf** [comment]
> @fbwoolf Attaching the network I selected which was directed to mainnet upon selection

That was the original image posted with the issue, but the list you are showing is the default list of networks. I don't see a custom network there?

**Comment by Eshwari007** [comment]
@fbwoolf I added the stacks.co api.regtest via WW.I only had mainnet and testnet on my list of networks.
Upon selecting the api regtest on explorer,the direction went to mainnet

**Comment by Eshwari007** [comment]
The above was in my WW,interestingly am not able to view the newly created network in explorer
<img width="425" alt="Screen Shot 2021-09-15 at 5 30 06 PM" src="https://user-images.githubusercontent.com/38872890/133512407-7b9764d8-0867-40a7-8d9b-f11e9e3633ae.png">

**Comment by fbwoolf** [comment]
This is expected behavior. Adding a network to the WW would only add it there. You would have to add it separately in the explorer.

**Comment by fbwoolf** [comment]
I will test this anyway and make sure it works now that I fixed the `Add a network` modal.

**Comment by fbwoolf** [comment]
This is not working, so good it was logged as an issue! Thx for helping to clarify.
