### ISSUE TITLE
How will images of smart contracts work?

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#55]
This is an open question: How will the images for smart contracts function? where are they hosted, how does one associate an image with a smart contract? Do we want to enforce any boundaries/rules?

cc @zone117x

**Comment by zone117x** [comment]
I think there are two options:

1. Define a `Clarity contract metadata` convention where something like an image URI and website could be defined. For example 
```
(define-constant meta-logo <uri>)
(define-constant meta-website <domain name string>)
```
2. Generate images based on the source code hash, like a gravatar

**Comment by jeffdomke** [comment]
@jasperjansz would like a solution for no images. We can always add this later but I don't want us to be forced to prioritize simply because we did not plan for it.

**Comment by jasperjansz** [comment]
Have them define a URL with max. 120px width and height. Common image extensions (jpg, png, etc.). 

If they don't show generic contract icon: https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=260%3A1732
