### ISSUE TITLE
Address links

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#56]
Currently the designs show that you can click on an address. We don't have a page designed for addresses. Where will the link go to?

<img width="880" alt="Screen Shot 2020-04-07 at 8 56 51 AM" src="https://user-images.githubusercontent.com/11803153/78677763-bcc62900-78ad-11ea-8fd2-f8b456095a11.png">

cc @jasperjansz @zone117x

**Comment by jasperjansz** [comment]
Nowhere currently — we can leave this out for now.
