### ISSUE TITLE
Fetch data from staging sidecar

### ISSUE THREAD

**Issue by aulneau** [blockstack/explorer#62]
We now have a staging instance for the sidecar to pull data from, we should fetch tx data from that.

**Comment by kyranjamie** [comment]
Can we configure environment variables with now?

**Comment by aulneau** [comment]
yeah! this just came out https://zeit.co/blog/environment-variables-ui

**Comment by timstackblock** [comment]
@kyranjamie Is there anything ready to QA in this ticket, or was meant for the code review swim lane?

**Comment by kyranjamie** [comment]
Hey @timstackblock — this was quite a broad task, the only thing to really check here is that there's a connection between (there should be)
- FE: https://explorer-silk.now.sh/
- BE: http://crashy-stacky.zone117x.com/tx

**Comment by timstackblock** [comment]
Thanks @kyranjamie we are currently getting a 502 error on the BE. 

<img width="1414" alt="Screen Shot 2020-04-20 at 9 55 37 AM" src="https://user-images.githubusercontent.com/49165468/79759944-526da980-82ed-11ea-8e5d-1db825133f73.png">

**Comment by kyranjamie** [comment]
@timstackblock bad timing, see [devx channel](https://blockstackpbc.slack.com/archives/CHY9G2PP1/p1587390599160500) message for info — should work now
