### ISSUE TITLE
Explorer Testing Placeholder

### ISSUE THREAD

**Issue by timstackblock** [blockstack/explorer#70]
Began reviewing the staging explorer at https://explorer-silk.now.sh/

Currently there is an issue where somethings don't work because of https mixed content. Functionality is limited but I can connect to API http://crashy-stacky.zone117x.com/tx and return info for some of the tx_id but no other data points.

The URL below returns valid data 
https://explorer-silk.now.sh/txid/0xeaf47b0d9b4a7439ff46943ac313637e3484c2393729da49fceac0d04d4d1ce0

@kyranjamie will let me know when the explorer is functional and ready for test.

**Comment by zone117x** [comment]
Any given transaction is _very_ ephemeral for now and should not be expected to exist for more than an hour. This is due to instability in the stack that requires wiping all data. 

This situation will be improved as core-node stabilizes. Track relevant issues:
https://github.com/blockstack/stacks-blockchain/issues/1130
https://github.com/blockstack/stacks-blockchain/issues/1402
https://github.com/blockstack/stacks-blockchain/issues/1418

**Comment by timstackblock** [comment]
Thanks for the info @zone117x I am not writing any bugs at the current moment, as the explorer is not is a testable state. Just wanted to get an issue up for communication as we move towards the QA phase. 

Thanks for linking the related blockchain issues as soon as the core node is up and running I will give it a first pass.

**Comment by timstackblock** [comment]
Hey guys just following up, are there any updates on testable functionality that I can get started with this week?

**Comment by aulneau** [comment]
ok third time is the charm :) 

@timstackblock I will write up a document today outlining how to properly test the explorer and send it over to you once it's ready

**Comment by timstackblock** [comment]
Thanks @aulneau I will use that to finalize test cases and let you know if I have any questions?

**Comment by timstackblock** [comment]
![image (8).png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/847e20ae-c861-46fc-901c-266dc0ae32bb)

**Comment by timstackblock** [comment]
![Screen Shot 2020-05-15 at 10.56.51 AM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/60ae3cdd-7c5d-41a4-9e7e-ad7d68fef9cb)

**Comment by timstackblock** [comment]
Twitter meta data does not show the blockstack logo image


![Screen Shot 2020-05-17 at 1.13.28 PM.png](https://images.zenhubusercontent.com/5ca24ab84ae8ce257af826b8/a2533b66-9d97-4984-8127-4204576149b7)

**Comment by timstackblock** [comment]
Just storing the output from the google schema test run this is not a bug

<img width="1439" alt="Screen Shot 2020-05-17 at 1 30 42 PM" src="https://user-images.githubusercontent.com/49165468/82155398-b8911200-9842-11ea-8dd5-d1b02a7fc638.png">
